	.align 2
voicegroup204:: @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano36, 255, 249, 0, 225	@ 127/ 75/  1/110/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano48, 255, 249, 0, 208	@ 127/ 75/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano60, 255, 249, 0, 208	@ 127/ 80/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano72, 255, 248, 0, 208	@ 127/ 85/  1/116/ 64
