#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define OBJ_EVENT_GFX_BRENDAN_NORMAL               0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE            1
#define OBJ_EVENT_GFX_BRENDAN_SURFING              2
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE           3
#define OBJ_EVENT_GFX_QUINTY_PLUMP                 4
#define OBJ_EVENT_GFX_NINJA_BOY                    5
#define OBJ_EVENT_GFX_TWIN                         6
#define OBJ_EVENT_GFX_BOY_1                        7
#define OBJ_EVENT_GFX_GIRL_1                       8
#define OBJ_EVENT_GFX_BOY_2                        9
#define OBJ_EVENT_GFX_GIRL_2                      10
#define OBJ_EVENT_GFX_LITTLE_BOY                  11
#define OBJ_EVENT_GFX_LITTLE_GIRL                 12
#define OBJ_EVENT_GFX_BOY_3                       13
#define OBJ_EVENT_GFX_GIRL_3                      14
#define OBJ_EVENT_GFX_RICH_BOY                    15
#define OBJ_EVENT_GFX_WOMAN_1                     16
#define OBJ_EVENT_GFX_FAT_MAN                     17
#define OBJ_EVENT_GFX_POKEFAN_F                   18
#define OBJ_EVENT_GFX_MAN_1                       19
#define OBJ_EVENT_GFX_WOMAN_2                     20
#define OBJ_EVENT_GFX_EXPERT_M                    21
#define OBJ_EVENT_GFX_EXPERT_F                    22
#define OBJ_EVENT_GFX_MAN_2                       23
#define OBJ_EVENT_GFX_WOMAN_3                     24
#define OBJ_EVENT_GFX_POKEFAN_M                   25
#define OBJ_EVENT_GFX_WOMAN_4                     26
#define OBJ_EVENT_GFX_COOK                        27
#define OBJ_EVENT_GFX_LINK_RECEPTIONIST           28
#define OBJ_EVENT_GFX_OLD_MAN                     29
#define OBJ_EVENT_GFX_OLD_WOMAN                   30
#define OBJ_EVENT_GFX_CAMPER                      31
#define OBJ_EVENT_GFX_PICNICKER                   32
#define OBJ_EVENT_GFX_MAN_3                       33
#define OBJ_EVENT_GFX_WOMAN_5                     34
#define OBJ_EVENT_GFX_YOUNGSTER                   35
#define OBJ_EVENT_GFX_BUG_CATCHER                 36
#define OBJ_EVENT_GFX_PSYCHIC_M                   37
#define OBJ_EVENT_GFX_SCHOOL_KID_M                38
#define OBJ_EVENT_GFX_MANIAC                      39
#define OBJ_EVENT_GFX_HEX_MANIAC                  40
#define OBJ_EVENT_GFX_RAYQUAZA_STILL              41
#define OBJ_EVENT_GFX_SWIMMER_M                   42
#define OBJ_EVENT_GFX_SWIMMER_F                   43
#define OBJ_EVENT_GFX_BLACK_BELT                  44
#define OBJ_EVENT_GFX_BEAUTY                      45
#define OBJ_EVENT_GFX_SCIENTIST_1                 46
#define OBJ_EVENT_GFX_LASS                        47
#define OBJ_EVENT_GFX_GENTLEMAN                   48
#define OBJ_EVENT_GFX_SAILOR                      49
#define OBJ_EVENT_GFX_FISHERMAN                   50
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M        51
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F        52
#define OBJ_EVENT_GFX_TUBER_F                     53
#define OBJ_EVENT_GFX_TUBER_M                     54
#define OBJ_EVENT_GFX_HIKER                       55
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M        56
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F        57
#define OBJ_EVENT_GFX_NURSE                       58
#define OBJ_EVENT_GFX_ITEM_BALL                   59
#define OBJ_EVENT_GFX_BERRY_TREE                  60
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES     61
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES      62
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE           63
#define OBJ_EVENT_GFX_PROF_BIRCH                  64
#define OBJ_EVENT_GFX_MAN_4                       65
#define OBJ_EVENT_GFX_MAN_5                       66
#define OBJ_EVENT_GFX_REPORTER_M                  67
#define OBJ_EVENT_GFX_REPORTER_F                  68
#define OBJ_EVENT_GFX_BARD                        69
#define OBJ_EVENT_GFX_ANABEL                      70
#define OBJ_EVENT_GFX_TUCKER                      71
#define OBJ_EVENT_GFX_GRETA                       72
#define OBJ_EVENT_GFX_SPENSER                     73
#define OBJ_EVENT_GFX_NOLAND                      74
#define OBJ_EVENT_GFX_LUCY                        75
#define OBJ_EVENT_GFX_UNUSED_NATU_DOLL            76
#define OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL       77
#define OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL        78
#define OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL          79
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL         80
#define OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL        81
#define OBJ_EVENT_GFX_CUTTABLE_TREE               82
#define OBJ_EVENT_GFX_MART_EMPLOYEE               83
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN          84
#define OBJ_EVENT_GFX_TEALA                       85
#define OBJ_EVENT_GFX_BREAKABLE_ROCK              86
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER            87
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT             88
#define OBJ_EVENT_GFX_MAY_NORMAL                  89
#define OBJ_EVENT_GFX_MAY_MACH_BIKE               90
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE               91
#define OBJ_EVENT_GFX_MAY_SURFING                 92
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE              93
#define OBJ_EVENT_GFX_TRUCK                       94
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX       95
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY        96
#define OBJ_EVENT_GFX_BIRCHS_BAG                  97
#define OBJ_EVENT_GFX_ZIGZAGOON_1                 98
#define OBJ_EVENT_GFX_ARTIST                      99
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL       100
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE    101
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE    102
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING      103
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE   104
#define OBJ_EVENT_GFX_RIVAL_MAY_NORMAL           105
#define OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE        106
#define OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE        107
#define OBJ_EVENT_GFX_RIVAL_MAY_SURFING          108
#define OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE       109
#define OBJ_EVENT_GFX_CAMERAMAN                  110
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER         111
#define OBJ_EVENT_GFX_MAY_UNDERWATER             112
#define OBJ_EVENT_GFX_MOVING_BOX                 113
#define OBJ_EVENT_GFX_CABLE_CAR                  114
#define OBJ_EVENT_GFX_SCIENTIST_2                115
#define OBJ_EVENT_GFX_DEVON_EMPLOYEE             116
#define OBJ_EVENT_GFX_AQUA_MEMBER_M              117
#define OBJ_EVENT_GFX_AQUA_MEMBER_F              118
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M             119
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F             120
#define OBJ_EVENT_GFX_SIDNEY                     121
#define OBJ_EVENT_GFX_PHOEBE                     122
#define OBJ_EVENT_GFX_GLACIA                     123
#define OBJ_EVENT_GFX_DRAKE                      124
#define OBJ_EVENT_GFX_ROXANNE                    125
#define OBJ_EVENT_GFX_BRAWLY                     126
#define OBJ_EVENT_GFX_WATTSON                    127
#define OBJ_EVENT_GFX_FLANNERY                   128
#define OBJ_EVENT_GFX_NORMAN                     129
#define OBJ_EVENT_GFX_WINONA                     130
#define OBJ_EVENT_GFX_LIZA                       131
#define OBJ_EVENT_GFX_TATE                       132
#define OBJ_EVENT_GFX_WALLACE                    133
#define OBJ_EVENT_GFX_STEVEN                     134
#define OBJ_EVENT_GFX_WALLY                      135
#define OBJ_EVENT_GFX_LITTLE_BOY_3               136
#define OBJ_EVENT_GFX_BRENDAN_FISHING            137
#define OBJ_EVENT_GFX_MAY_FISHING                138
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN      139
#define OBJ_EVENT_GFX_SS_TIDAL                   140
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW           141
#define OBJ_EVENT_GFX_PICHU_DOLL                 142
#define OBJ_EVENT_GFX_PIKACHU_DOLL               143
#define OBJ_EVENT_GFX_MARILL_DOLL                144
#define OBJ_EVENT_GFX_TOGEPI_DOLL                145
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL             146
#define OBJ_EVENT_GFX_CHIKORITA_DOLL             147
#define OBJ_EVENT_GFX_TOTODILE_DOLL              148
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL            149
#define OBJ_EVENT_GFX_MEOWTH_DOLL                150
#define OBJ_EVENT_GFX_CLEFAIRY_DOLL              151
#define OBJ_EVENT_GFX_DITTO_DOLL                 152
#define OBJ_EVENT_GFX_SMOOCHUM_DOLL              153
#define OBJ_EVENT_GFX_TREECKO_DOLL               154
#define OBJ_EVENT_GFX_TORCHIC_DOLL               155
#define OBJ_EVENT_GFX_MUDKIP_DOLL                156
#define OBJ_EVENT_GFX_DUSKULL_DOLL               157
#define OBJ_EVENT_GFX_WYNAUT_DOLL                158
#define OBJ_EVENT_GFX_BALTOY_DOLL                159
#define OBJ_EVENT_GFX_KECLEON_DOLL               160
#define OBJ_EVENT_GFX_AZURILL_DOLL               161
#define OBJ_EVENT_GFX_SKITTY_DOLL                162
#define OBJ_EVENT_GFX_SWABLU_DOLL                163
#define OBJ_EVENT_GFX_GULPIN_DOLL                164
#define OBJ_EVENT_GFX_LOTAD_DOLL                 165
#define OBJ_EVENT_GFX_SEEDOT_DOLL                166
#define OBJ_EVENT_GFX_PIKA_CUSHION               167
#define OBJ_EVENT_GFX_ROUND_CUSHION              168
#define OBJ_EVENT_GFX_KISS_CUSHION               169
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION             170
#define OBJ_EVENT_GFX_SPIN_CUSHION               171
#define OBJ_EVENT_GFX_DIAMOND_CUSHION            172
#define OBJ_EVENT_GFX_BALL_CUSHION               173
#define OBJ_EVENT_GFX_GRASS_CUSHION              174
#define OBJ_EVENT_GFX_FIRE_CUSHION               175
#define OBJ_EVENT_GFX_WATER_CUSHION              176
#define OBJ_EVENT_GFX_BIG_SNORLAX_DOLL           177
#define OBJ_EVENT_GFX_BIG_RHYDON_DOLL            178
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL            179
#define OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL          180
#define OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL         181
#define OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL         182
#define OBJ_EVENT_GFX_BIG_WAILMER_DOLL           183
#define OBJ_EVENT_GFX_BIG_REGIROCK_DOLL          184
#define OBJ_EVENT_GFX_BIG_REGICE_DOLL            185
#define OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL         186
#define OBJ_EVENT_GFX_LATIAS                     187
#define OBJ_EVENT_GFX_LATIOS                     188
#define OBJ_EVENT_GFX_GAMEBOY_KID                189
#define OBJ_EVENT_GFX_CONTEST_JUDGE              190
#define OBJ_EVENT_GFX_BRENDAN_WATERING           191
#define OBJ_EVENT_GFX_MAY_WATERING               192
#define OBJ_EVENT_GFX_BRENDAN_DECORATING         193
#define OBJ_EVENT_GFX_MAY_DECORATING             194
#define OBJ_EVENT_GFX_ARCHIE                     195
#define OBJ_EVENT_GFX_MAXIE                      196
#define OBJ_EVENT_GFX_KYOGRE_FRONT               197
#define OBJ_EVENT_GFX_GROUDON_FRONT              198
#define OBJ_EVENT_GFX_FOSSIL                     199
#define OBJ_EVENT_GFX_REGIROCK                   200
#define OBJ_EVENT_GFX_REGICE                     201
#define OBJ_EVENT_GFX_REGISTEEL                  202
#define OBJ_EVENT_GFX_SKITTY                     203
#define OBJ_EVENT_GFX_KECLEON                    204
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP              205
#define OBJ_EVENT_GFX_GROUDON_ASLEEP             206
#define OBJ_EVENT_GFX_RAYQUAZA                   207
#define OBJ_EVENT_GFX_ZIGZAGOON_2                208
#define OBJ_EVENT_GFX_PIKACHU                    209
#define OBJ_EVENT_GFX_AZUMARILL                  210
#define OBJ_EVENT_GFX_WINGULL                    211
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW      212
#define OBJ_EVENT_GFX_TUBER_M_SWIMMING           213
#define OBJ_EVENT_GFX_AZURILL                    214
#define OBJ_EVENT_GFX_MOM                        215
#define OBJ_EVENT_GFX_LINK_BRENDAN               216
#define OBJ_EVENT_GFX_LINK_MAY                   217
#define OBJ_EVENT_GFX_JUAN                       218
#define OBJ_EVENT_GFX_SCOTT                      219
#define OBJ_EVENT_GFX_POOCHYENA                  220
#define OBJ_EVENT_GFX_KYOGRE_SIDE                221
#define OBJ_EVENT_GFX_GROUDON_SIDE               222
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN           223
#define OBJ_EVENT_GFX_TRICK_HOUSE_STATUE         224
#define OBJ_EVENT_GFX_KIRLIA                     225
#define OBJ_EVENT_GFX_DUSCLOPS                   226
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE           227
#define OBJ_EVENT_GFX_SUDOWOODO                  228
#define OBJ_EVENT_GFX_MEW                        229
#define OBJ_EVENT_GFX_RED                        230
#define OBJ_EVENT_GFX_LEAF                       231
#define OBJ_EVENT_GFX_DEOXYS                     232
#define OBJ_EVENT_GFX_DEOXYS_TRIANGLE            233
#define OBJ_EVENT_GFX_BRANDON                    234
#define OBJ_EVENT_GFX_LINK_RS_BRENDAN            235
#define OBJ_EVENT_GFX_LINK_RS_MAY                236
#define OBJ_EVENT_GFX_LUGIA                      237
#define OBJ_EVENT_GFX_HOOH                       238

#define NUM_ORIG_OBJ_EVENT_GFX                   239

// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VAR_FIRST   (NUM_ORIG_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VAR_FIRST + 0x0) // 240
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VAR_FIRST + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VAR_FIRST + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VAR_FIRST + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VAR_FIRST + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VAR_FIRST + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VAR_FIRST + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VAR_FIRST + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VAR_FIRST + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VAR_FIRST + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VAR_FIRST + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VAR_FIRST + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VAR_FIRST + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VAR_FIRST + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VAR_FIRST + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VAR_FIRST + 0xF) // 255
#define OBJ_EVENT_GFX_VAR_LAST   OBJ_EVENT_GFX_VAR_F

// RogueNote: Additional GFX, just gonna put them after this to avoid shifting the OG IDs about

// This is the new avatar obj (The actual gfx will be repointed to based on player customisation options)
#define OBJ_EVENT_GFX_PLAYER_NORMAL              (OBJ_EVENT_GFX_VAR_F + 1)
#define OBJ_EVENT_GFX_PLAYER_RIDING              (OBJ_EVENT_GFX_VAR_F + 2)
#define OBJ_EVENT_GFX_PLAYER_FIELD_MOVE          (OBJ_EVENT_GFX_VAR_F + 3)

#define OBJ_EVENT_GFX_PLAYER_FIRST               OBJ_EVENT_GFX_PLAYER_NORMAL
#define OBJ_EVENT_GFX_PLAYER_LAST                OBJ_EVENT_GFX_PLAYER_FIELD_MOVE

#define OBJ_EVENT_GFX_NET_PLAYER_NORMAL          (OBJ_EVENT_GFX_PLAYER_LAST + 1)
#define OBJ_EVENT_GFX_NET_PLAYER_RIDING          (OBJ_EVENT_GFX_PLAYER_LAST + 2)
//#define OBJ_EVENT_GFX_NET_PLAYER_FIELD_MOVE      (OBJ_EVENT_GFX_PLAYER_LAST + 3)

#define OBJ_EVENT_GFX_NET_PLAYER_FIRST           OBJ_EVENT_GFX_NET_PLAYER_NORMAL
#define OBJ_EVENT_GFX_NET_PLAYER_LAST            OBJ_EVENT_GFX_NET_PLAYER_RIDING


#define OBJ_EVENT_GFX_MAY_RIDING                 (OBJ_EVENT_GFX_NET_PLAYER_LAST + 1)
#define OBJ_EVENT_GFX_BRENDAN_RIDING             (OBJ_EVENT_GFX_NET_PLAYER_LAST + 2)

#define OBJ_EVENT_GFX_LEAF_MACH_BIKE             (OBJ_EVENT_GFX_BRENDAN_RIDING + 1)
#define OBJ_EVENT_GFX_LEAF_ACRO_BIKE             (OBJ_EVENT_GFX_BRENDAN_RIDING + 2)
#define OBJ_EVENT_GFX_LEAF_SURFING               (OBJ_EVENT_GFX_BRENDAN_RIDING + 3)
#define OBJ_EVENT_GFX_LEAF_FIELD_MOVE            (OBJ_EVENT_GFX_BRENDAN_RIDING + 4)
#define OBJ_EVENT_GFX_LEAF_FISHING               (OBJ_EVENT_GFX_BRENDAN_RIDING + 5)
#define OBJ_EVENT_GFX_LEAF_RIDING                (OBJ_EVENT_GFX_BRENDAN_RIDING + 6)

#define OBJ_EVENT_GFX_RED_MACH_BIKE              (OBJ_EVENT_GFX_LEAF_RIDING + 1)
#define OBJ_EVENT_GFX_RED_ACRO_BIKE              (OBJ_EVENT_GFX_LEAF_RIDING + 2)
#define OBJ_EVENT_GFX_RED_SURFING                (OBJ_EVENT_GFX_LEAF_RIDING + 3)
#define OBJ_EVENT_GFX_RED_FIELD_MOVE             (OBJ_EVENT_GFX_LEAF_RIDING + 4)
#define OBJ_EVENT_GFX_RED_FISHING                (OBJ_EVENT_GFX_LEAF_RIDING + 5)
#define OBJ_EVENT_GFX_RED_RIDING                 (OBJ_EVENT_GFX_LEAF_RIDING + 6)

#define OBJ_EVENT_GFX_LYRA                       (OBJ_EVENT_GFX_RED_RIDING + 1)
#define OBJ_EVENT_GFX_LYRA_MACH_BIKE             (OBJ_EVENT_GFX_RED_RIDING + 2)
#define OBJ_EVENT_GFX_LYRA_ACRO_BIKE             (OBJ_EVENT_GFX_RED_RIDING + 3)
#define OBJ_EVENT_GFX_LYRA_SURFING               (OBJ_EVENT_GFX_RED_RIDING + 4)
#define OBJ_EVENT_GFX_LYRA_FIELD_MOVE            (OBJ_EVENT_GFX_RED_RIDING + 5)
#define OBJ_EVENT_GFX_LYRA_FISHING               (OBJ_EVENT_GFX_RED_RIDING + 6)
#define OBJ_EVENT_GFX_LYRA_RIDING                (OBJ_EVENT_GFX_RED_RIDING + 7)

#define OBJ_EVENT_GFX_ETHAN                      (OBJ_EVENT_GFX_LYRA_RIDING + 1)
#define OBJ_EVENT_GFX_ETHAN_MACH_BIKE            (OBJ_EVENT_GFX_LYRA_RIDING + 2)
#define OBJ_EVENT_GFX_ETHAN_ACRO_BIKE            (OBJ_EVENT_GFX_LYRA_RIDING + 3)
#define OBJ_EVENT_GFX_ETHAN_SURFING              (OBJ_EVENT_GFX_LYRA_RIDING + 4)
#define OBJ_EVENT_GFX_ETHAN_FIELD_MOVE           (OBJ_EVENT_GFX_LYRA_RIDING + 5)
#define OBJ_EVENT_GFX_ETHAN_FISHING              (OBJ_EVENT_GFX_LYRA_RIDING + 6)
#define OBJ_EVENT_GFX_ETHAN_RIDING               (OBJ_EVENT_GFX_LYRA_RIDING + 7)

// Net player alternate
#define OBJ_EVENT_GFX_BUG_CATCHER_RIDING         (OBJ_EVENT_GFX_ETHAN_RIDING + 1)

#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_01         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 1)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_02         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 2)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_03         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 3)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_04         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 4)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_05         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 5)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_06         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 6)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_07         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 7)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_08         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 8)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_09         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 9)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_10         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 10)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_11         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 11)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_12         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 12)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_13         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 13)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_14         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 14)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_15         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 15)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_16         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 16)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_17         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 17)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_18         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 18)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_19         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 19)
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_20         (OBJ_EVENT_GFX_BUG_CATCHER_RIDING + 20)

#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_FIRST      OBJ_EVENT_GFX_DYNAMIC_TRAINER_01
#define OBJ_EVENT_GFX_DYNAMIC_TRAINER_LAST       OBJ_EVENT_GFX_DYNAMIC_TRAINER_20

#define OBJ_EVENT_GFX_BIKER                      (OBJ_EVENT_GFX_DYNAMIC_TRAINER_20 + 1)
#define OBJ_EVENT_GFX_OLD_MAN_2                  (OBJ_EVENT_GFX_DYNAMIC_TRAINER_20 + 2)
#define OBJ_EVENT_GFX_ROCKET_F                   (OBJ_EVENT_GFX_DYNAMIC_TRAINER_20 + 3)
#define OBJ_EVENT_GFX_ROCKET_M                   (OBJ_EVENT_GFX_DYNAMIC_TRAINER_20 + 4)
#define OBJ_EVENT_GFX_BILL                       (OBJ_EVENT_GFX_DYNAMIC_TRAINER_20 + 5)

#define OBJ_EVENT_GFX_KANTO_AGATHA               (OBJ_EVENT_GFX_BILL + 1)
#define OBJ_EVENT_GFX_KANTO_BLAINE               (OBJ_EVENT_GFX_BILL + 2)
#define OBJ_EVENT_GFX_KANTO_BLUE                 (OBJ_EVENT_GFX_BILL + 3)
#define OBJ_EVENT_GFX_KANTO_BROCK                (OBJ_EVENT_GFX_BILL + 4)
#define OBJ_EVENT_GFX_KANTO_BRUNO                (OBJ_EVENT_GFX_BILL + 5)
#define OBJ_EVENT_GFX_KANTO_ERIKA                (OBJ_EVENT_GFX_BILL + 6)
#define OBJ_EVENT_GFX_KANTO_GIOVANNI             (OBJ_EVENT_GFX_BILL + 7)
#define OBJ_EVENT_GFX_KANTO_KOGA                 (OBJ_EVENT_GFX_BILL + 8)
#define OBJ_EVENT_GFX_KANTO_LANCE                (OBJ_EVENT_GFX_BILL + 9)
#define OBJ_EVENT_GFX_KANTO_LORELEI              (OBJ_EVENT_GFX_BILL + 10)
#define OBJ_EVENT_GFX_KANTO_LTSURGE              (OBJ_EVENT_GFX_BILL + 11)
#define OBJ_EVENT_GFX_KANTO_MISTY                (OBJ_EVENT_GFX_BILL + 12)
#define OBJ_EVENT_GFX_KANTO_PROFOAK              (OBJ_EVENT_GFX_BILL + 13)
#define OBJ_EVENT_GFX_KANTO_SABRINA              (OBJ_EVENT_GFX_BILL + 14)
#define OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI      (OBJ_EVENT_GFX_BILL + 15)

#define OBJ_EVENT_GFX_JOHTO_BUGSY                (OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI + 1)
#define OBJ_EVENT_GFX_JOHTO_CLAIR                (OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI + 2)
#define OBJ_EVENT_GFX_JOHTO_CHUCK                (OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI + 3)
#define OBJ_EVENT_GFX_JOHTO_FALKNER              (OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI + 4)
#define OBJ_EVENT_GFX_JOHTO_JASMINE              (OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI + 5)
#define OBJ_EVENT_GFX_JOHTO_KAREN                (OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI + 6)
#define OBJ_EVENT_GFX_JOHTO_MORTY                (OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI + 7)
#define OBJ_EVENT_GFX_JOHTO_PRYCE                (OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI + 8)
#define OBJ_EVENT_GFX_JOHTO_WHITNEY              (OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI + 9)
#define OBJ_EVENT_GFX_JOHTO_WILL                 (OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI + 10)
#define OBJ_EVENT_GFX_JOHTO_RED                  (OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI + 11)

#define OBJ_EVENT_GFX_SINNOH_AARON               (OBJ_EVENT_GFX_JOHTO_RED + 1)
#define OBJ_EVENT_GFX_SINNOH_BERTHA              (OBJ_EVENT_GFX_JOHTO_RED + 2)
#define OBJ_EVENT_GFX_SINNOH_BYRON               (OBJ_EVENT_GFX_JOHTO_RED + 3)
#define OBJ_EVENT_GFX_SINNOH_CRASHER_WAKE        (OBJ_EVENT_GFX_JOHTO_RED + 4)
#define OBJ_EVENT_GFX_SINNOH_CYNTHIA             (OBJ_EVENT_GFX_JOHTO_RED + 5)
#define OBJ_EVENT_GFX_SINNOH_FANTINA             (OBJ_EVENT_GFX_JOHTO_RED + 6)
#define OBJ_EVENT_GFX_SINNOH_FLINT               (OBJ_EVENT_GFX_JOHTO_RED + 7)
#define OBJ_EVENT_GFX_SINNOH_GARDENIA            (OBJ_EVENT_GFX_JOHTO_RED + 8)
#define OBJ_EVENT_GFX_SINNOH_LUCIAN              (OBJ_EVENT_GFX_JOHTO_RED + 9)
#define OBJ_EVENT_GFX_SINNOH_ROARK               (OBJ_EVENT_GFX_JOHTO_RED + 10)
#define OBJ_EVENT_GFX_SINNOH_VOLKNER             (OBJ_EVENT_GFX_JOHTO_RED + 11)
#define OBJ_EVENT_GFX_SINNOH_CANDICE             (OBJ_EVENT_GFX_JOHTO_RED + 12)
#define OBJ_EVENT_GFX_SINNOH_MAYLENE             (OBJ_EVENT_GFX_JOHTO_RED + 13)

#define OBJ_EVENT_GFX_UNOVA_ALDER                (OBJ_EVENT_GFX_SINNOH_MAYLENE + 1)
#define OBJ_EVENT_GFX_UNOVA_BRYCEN               (OBJ_EVENT_GFX_SINNOH_MAYLENE + 2)
#define OBJ_EVENT_GFX_UNOVA_CAITLIN              (OBJ_EVENT_GFX_SINNOH_MAYLENE + 3)
#define OBJ_EVENT_GFX_UNOVA_CLAY                 (OBJ_EVENT_GFX_SINNOH_MAYLENE + 4)
#define OBJ_EVENT_GFX_UNOVA_DRAYDEN              (OBJ_EVENT_GFX_SINNOH_MAYLENE + 5)
#define OBJ_EVENT_GFX_UNOVA_ELESA                (OBJ_EVENT_GFX_SINNOH_MAYLENE + 6)
#define OBJ_EVENT_GFX_UNOVA_GRIMSLEY             (OBJ_EVENT_GFX_SINNOH_MAYLENE + 7)
#define OBJ_EVENT_GFX_UNOVA_IRIS                 (OBJ_EVENT_GFX_SINNOH_MAYLENE + 8)
#define OBJ_EVENT_GFX_UNOVA_LENORA               (OBJ_EVENT_GFX_SINNOH_MAYLENE + 9)
#define OBJ_EVENT_GFX_UNOVA_MARLON               (OBJ_EVENT_GFX_SINNOH_MAYLENE + 10)
#define OBJ_EVENT_GFX_UNOVA_MARSHAL              (OBJ_EVENT_GFX_SINNOH_MAYLENE + 11)
#define OBJ_EVENT_GFX_UNOVA_CHILI                (OBJ_EVENT_GFX_SINNOH_MAYLENE + 12)
#define OBJ_EVENT_GFX_UNOVA_CILAN                (OBJ_EVENT_GFX_SINNOH_MAYLENE + 13)
#define OBJ_EVENT_GFX_UNOVA_CRESS                (OBJ_EVENT_GFX_SINNOH_MAYLENE + 14)
#define OBJ_EVENT_GFX_UNOVA_SHAUNTAL             (OBJ_EVENT_GFX_SINNOH_MAYLENE + 15)
#define OBJ_EVENT_GFX_UNOVA_SKYLA                (OBJ_EVENT_GFX_SINNOH_MAYLENE + 16)
#define OBJ_EVENT_GFX_UNOVA_BURGH                (OBJ_EVENT_GFX_SINNOH_MAYLENE + 17)
#define OBJ_EVENT_GFX_UNOVA_ROXIE                (OBJ_EVENT_GFX_SINNOH_MAYLENE + 18)

#define OBJ_EVENT_GFX_KALOS_CLEMONT              (OBJ_EVENT_GFX_UNOVA_ROXIE + 1)
#define OBJ_EVENT_GFX_KALOS_DIANTHA              (OBJ_EVENT_GFX_UNOVA_ROXIE + 2)
#define OBJ_EVENT_GFX_KALOS_DRASNA               (OBJ_EVENT_GFX_UNOVA_ROXIE + 3)
#define OBJ_EVENT_GFX_KALOS_GRANT                (OBJ_EVENT_GFX_UNOVA_ROXIE + 4)
#define OBJ_EVENT_GFX_KALOS_KORRINA              (OBJ_EVENT_GFX_UNOVA_ROXIE + 5)
#define OBJ_EVENT_GFX_KALOS_MALVA                (OBJ_EVENT_GFX_UNOVA_ROXIE + 6)
#define OBJ_EVENT_GFX_KALOS_OLYMPIA              (OBJ_EVENT_GFX_UNOVA_ROXIE + 7)
#define OBJ_EVENT_GFX_KALOS_RAMOS                (OBJ_EVENT_GFX_UNOVA_ROXIE + 8)
#define OBJ_EVENT_GFX_KALOS_SIEBOLD              (OBJ_EVENT_GFX_UNOVA_ROXIE + 9)
#define OBJ_EVENT_GFX_KALOS_VALERIE              (OBJ_EVENT_GFX_UNOVA_ROXIE + 10)
#define OBJ_EVENT_GFX_KALOS_VIOLA                (OBJ_EVENT_GFX_UNOVA_ROXIE + 11)
#define OBJ_EVENT_GFX_KALOS_WIKSTROM             (OBJ_EVENT_GFX_UNOVA_ROXIE + 12)
#define OBJ_EVENT_GFX_KALOS_WULFRIC              (OBJ_EVENT_GFX_UNOVA_ROXIE + 13)

#define OBJ_EVENT_GFX_ALOLA_ACEROLA              (OBJ_EVENT_GFX_KALOS_WULFRIC + 1)
#define OBJ_EVENT_GFX_ALOLA_HALA                 (OBJ_EVENT_GFX_KALOS_WULFRIC + 2)
#define OBJ_EVENT_GFX_ALOLA_HAPU                 (OBJ_EVENT_GFX_KALOS_WULFRIC + 3)
#define OBJ_EVENT_GFX_ALOLA_ILIMA                (OBJ_EVENT_GFX_KALOS_WULFRIC + 4)
#define OBJ_EVENT_GFX_ALOLA_KAHILI               (OBJ_EVENT_GFX_KALOS_WULFRIC + 5)
#define OBJ_EVENT_GFX_ALOLA_KIAWE                (OBJ_EVENT_GFX_KALOS_WULFRIC + 6)
#define OBJ_EVENT_GFX_ALOLA_KUKUI                (OBJ_EVENT_GFX_KALOS_WULFRIC + 7)
#define OBJ_EVENT_GFX_ALOLA_LANA                 (OBJ_EVENT_GFX_KALOS_WULFRIC + 8)
#define OBJ_EVENT_GFX_ALOLA_MALLOW               (OBJ_EVENT_GFX_KALOS_WULFRIC + 9)
#define OBJ_EVENT_GFX_ALOLA_MINA                 (OBJ_EVENT_GFX_KALOS_WULFRIC + 10)
#define OBJ_EVENT_GFX_ALOLA_MOLAYNE              (OBJ_EVENT_GFX_KALOS_WULFRIC + 11)
#define OBJ_EVENT_GFX_ALOLA_NANU                 (OBJ_EVENT_GFX_KALOS_WULFRIC + 12)
#define OBJ_EVENT_GFX_ALOLA_OLIVIA               (OBJ_EVENT_GFX_KALOS_WULFRIC + 13)
#define OBJ_EVENT_GFX_ALOLA_SOPHOCLES            (OBJ_EVENT_GFX_KALOS_WULFRIC + 14)

#define OBJ_EVENT_GFX_GALAR_ALLISTER             (OBJ_EVENT_GFX_ALOLA_SOPHOCLES + 2)
#define OBJ_EVENT_GFX_GALAR_BEA                  (OBJ_EVENT_GFX_ALOLA_SOPHOCLES + 3)
#define OBJ_EVENT_GFX_GALAR_GORDIE               (OBJ_EVENT_GFX_ALOLA_SOPHOCLES + 4)
#define OBJ_EVENT_GFX_GALAR_KABU                 (OBJ_EVENT_GFX_ALOLA_SOPHOCLES + 5)
#define OBJ_EVENT_GFX_GALAR_LEON                 (OBJ_EVENT_GFX_ALOLA_SOPHOCLES + 6)
#define OBJ_EVENT_GFX_GALAR_MELONY               (OBJ_EVENT_GFX_ALOLA_SOPHOCLES + 7)
#define OBJ_EVENT_GFX_GALAR_MILO                 (OBJ_EVENT_GFX_ALOLA_SOPHOCLES + 8)
#define OBJ_EVENT_GFX_GALAR_NESSA                (OBJ_EVENT_GFX_ALOLA_SOPHOCLES + 9)
#define OBJ_EVENT_GFX_GALAR_OPAL                 (OBJ_EVENT_GFX_ALOLA_SOPHOCLES + 10)
#define OBJ_EVENT_GFX_GALAR_PIERS                (OBJ_EVENT_GFX_ALOLA_SOPHOCLES + 11)
#define OBJ_EVENT_GFX_GALAR_RAIHAN               (OBJ_EVENT_GFX_ALOLA_SOPHOCLES + 12)

#define OBJ_EVENT_GFX_PALDEA_BRASSIUS            (OBJ_EVENT_GFX_GALAR_RAIHAN + 1)
#define OBJ_EVENT_GFX_PALDEA_GRUSHA              (OBJ_EVENT_GFX_GALAR_RAIHAN + 2)
#define OBJ_EVENT_GFX_PALDEA_IONO                (OBJ_EVENT_GFX_GALAR_RAIHAN + 3)
#define OBJ_EVENT_GFX_PALDEA_KATY                (OBJ_EVENT_GFX_GALAR_RAIHAN + 4)
#define OBJ_EVENT_GFX_PALDEA_KOFU                (OBJ_EVENT_GFX_GALAR_RAIHAN + 5)
#define OBJ_EVENT_GFX_PALDEA_LARRY               (OBJ_EVENT_GFX_GALAR_RAIHAN + 6)
#define OBJ_EVENT_GFX_PALDEA_RYME                (OBJ_EVENT_GFX_GALAR_RAIHAN + 7)
#define OBJ_EVENT_GFX_PALDEA_GEETA               (OBJ_EVENT_GFX_GALAR_RAIHAN + 8)
#define OBJ_EVENT_GFX_PALDEA_HASSEL              (OBJ_EVENT_GFX_GALAR_RAIHAN + 9)
#define OBJ_EVENT_GFX_PALDEA_POPPY               (OBJ_EVENT_GFX_GALAR_RAIHAN + 10)
#define OBJ_EVENT_GFX_PALDEA_RIKA                (OBJ_EVENT_GFX_GALAR_RAIHAN + 11)
#define OBJ_EVENT_GFX_PALDEA_TULIP               (OBJ_EVENT_GFX_GALAR_RAIHAN + 12)

#define OBJ_EVENT_GFX_MISC_AROMA_GIRL            (OBJ_EVENT_GFX_PALDEA_TULIP + 1)
#define OBJ_EVENT_GFX_MISC_BACKPACKER_F          (OBJ_EVENT_GFX_PALDEA_TULIP + 2)
#define OBJ_EVENT_GFX_MISC_BACKPACKER_M          (OBJ_EVENT_GFX_PALDEA_TULIP + 3)
#define OBJ_EVENT_GFX_MISC_BUG_CATCHER           (OBJ_EVENT_GFX_PALDEA_TULIP + 4)
#define OBJ_EVENT_GFX_MISC_BURGLAR               (OBJ_EVENT_GFX_PALDEA_TULIP + 5)
#define OBJ_EVENT_GFX_MISC_CHANNELER             (OBJ_EVENT_GFX_PALDEA_TULIP + 6)
#define OBJ_EVENT_GFX_MISC_CLOWN                 (OBJ_EVENT_GFX_PALDEA_TULIP + 7)
#define OBJ_EVENT_GFX_MISC_HEX_MANIAC            (OBJ_EVENT_GFX_PALDEA_TULIP + 8)
#define OBJ_EVENT_GFX_MISC_KALOS_ENGINEER        (OBJ_EVENT_GFX_PALDEA_TULIP + 9)
#define OBJ_EVENT_GFX_MISC_KALOS_WORKER          (OBJ_EVENT_GFX_PALDEA_TULIP + 10)
#define OBJ_EVENT_GFX_MISC_LOOKER                (OBJ_EVENT_GFX_PALDEA_TULIP + 11)
#define OBJ_EVENT_GFX_MISC_NPC_LADY              (OBJ_EVENT_GFX_PALDEA_TULIP + 12)
#define OBJ_EVENT_GFX_MISC_NPC_MYSTERY_GIFT      (OBJ_EVENT_GFX_PALDEA_TULIP + 13)
#define OBJ_EVENT_GFX_MISC_NPC_TUTOR             (OBJ_EVENT_GFX_PALDEA_TULIP + 14)
#define OBJ_EVENT_GFX_MISC_NURSE                 (OBJ_EVENT_GFX_PALDEA_TULIP + 15)
#define OBJ_EVENT_GFX_MISC_PEONIA                (OBJ_EVENT_GFX_PALDEA_TULIP + 16)
#define OBJ_EVENT_GFX_MISC_POKE_FAN_F            (OBJ_EVENT_GFX_PALDEA_TULIP + 17)
#define OBJ_EVENT_GFX_MISC_PROFESSOR_ELM         (OBJ_EVENT_GFX_PALDEA_TULIP + 18)
#define OBJ_EVENT_GFX_MISC_RUIN_MANIAC           (OBJ_EVENT_GFX_PALDEA_TULIP + 19)
#define OBJ_EVENT_GFX_MISC_SCIENTIST             (OBJ_EVENT_GFX_PALDEA_TULIP + 20)
#define OBJ_EVENT_GFX_MISC_SUPER_NERD            (OBJ_EVENT_GFX_PALDEA_TULIP + 21)
#define OBJ_EVENT_GFX_MISC_UNOVA_SCIENTIST_F     (OBJ_EVENT_GFX_PALDEA_TULIP + 22)
#define OBJ_EVENT_GFX_MISC_VETERAN               (OBJ_EVENT_GFX_PALDEA_TULIP + 23)
#define OBJ_EVENT_GFX_MISC_YOUNG_COUPLE_F        (OBJ_EVENT_GFX_PALDEA_TULIP + 24)
#define OBJ_EVENT_GFX_MISC_YOUNG_COUPLE_M        (OBJ_EVENT_GFX_PALDEA_TULIP + 25)
#define OBJ_EVENT_GFX_MISC_HEX_MANIAC_SECRET     (OBJ_EVENT_GFX_PALDEA_TULIP + 26)
#define OBJ_EVENT_GFX_MISC_BALL_GUY              (OBJ_EVENT_GFX_PALDEA_TULIP + 27)

#define OBJ_EVENT_GFX_RIVAL_AVERY                (OBJ_EVENT_GFX_MISC_BALL_GUY + 1)
#define OBJ_EVENT_GFX_RIVAL_BARRY                (OBJ_EVENT_GFX_MISC_BALL_GUY + 2)
#define OBJ_EVENT_GFX_RIVAL_BEDE                 (OBJ_EVENT_GFX_MISC_BALL_GUY + 3)
#define OBJ_EVENT_GFX_RIVAL_BIANCA               (OBJ_EVENT_GFX_MISC_BALL_GUY + 4)
#define OBJ_EVENT_GFX_RIVAL_CHEREN               (OBJ_EVENT_GFX_MISC_BALL_GUY + 5)
#define OBJ_EVENT_GFX_RIVAL_GLADION              (OBJ_EVENT_GFX_MISC_BALL_GUY + 6)
#define OBJ_EVENT_GFX_RIVAL_HAU                  (OBJ_EVENT_GFX_MISC_BALL_GUY + 7)
#define OBJ_EVENT_GFX_RIVAL_HOP                  (OBJ_EVENT_GFX_MISC_BALL_GUY + 8)
#define OBJ_EVENT_GFX_RIVAL_HUGH                 (OBJ_EVENT_GFX_MISC_BALL_GUY + 9)
#define OBJ_EVENT_GFX_RIVAL_KLARA                (OBJ_EVENT_GFX_MISC_BALL_GUY + 10)
#define OBJ_EVENT_GFX_RIVAL_MARNIE               (OBJ_EVENT_GFX_MISC_BALL_GUY + 11)
#define OBJ_EVENT_GFX_RIVAL_N                    (OBJ_EVENT_GFX_MISC_BALL_GUY + 12)
#define OBJ_EVENT_GFX_RIVAL_SHAUNA               (OBJ_EVENT_GFX_MISC_BALL_GUY + 13)
#define OBJ_EVENT_GFX_RIVAL_SILVER               (OBJ_EVENT_GFX_MISC_BALL_GUY + 14)
#define OBJ_EVENT_GFX_RIVAL_TIERNO               (OBJ_EVENT_GFX_MISC_BALL_GUY + 15)
#define OBJ_EVENT_GFX_RIVAL_TREVOR               (OBJ_EVENT_GFX_MISC_BALL_GUY + 16)
#define OBJ_EVENT_GFX_RIVAL_NEMONA               (OBJ_EVENT_GFX_MISC_BALL_GUY + 17)
#define OBJ_EVENT_GFX_RIVAL_PENNY                (OBJ_EVENT_GFX_MISC_BALL_GUY + 18)
#define OBJ_EVENT_GFX_RIVAL_ARVEN                (OBJ_EVENT_GFX_MISC_BALL_GUY + 19)

#define OBJ_EVENT_GFX_PC                         (OBJ_EVENT_GFX_RIVAL_ARVEN + 1)
#define OBJ_EVENT_GFX_PC_STAND                   (OBJ_EVENT_GFX_RIVAL_ARVEN + 2)
#define OBJ_EVENT_GFX_BATTLE_STATUE              (OBJ_EVENT_GFX_RIVAL_ARVEN + 3)
#define OBJ_EVENT_GFX_PHONE_BOOTH                (OBJ_EVENT_GFX_RIVAL_ARVEN + 4)
#define OBJ_EVENT_GFX_POKEBLOCK_MIXER            (OBJ_EVENT_GFX_RIVAL_ARVEN + 5)
#define OBJ_EVENT_GFX_POKEBLOCK_MIXER_GOLD       (OBJ_EVENT_GFX_RIVAL_ARVEN + 6)
#define OBJ_EVENT_GFX_FOOD_PIE                   (OBJ_EVENT_GFX_RIVAL_ARVEN + 7)
#define OBJ_EVENT_GFX_SMALL_SIGN                 (OBJ_EVENT_GFX_RIVAL_ARVEN + 8)
#define OBJ_EVENT_GFX_DEVIL_MAN                  (OBJ_EVENT_GFX_RIVAL_ARVEN + 9)
#define OBJ_EVENT_GFX_WORK_TABLE                 (OBJ_EVENT_GFX_RIVAL_ARVEN + 10)
#define OBJ_EVENT_GFX_QUEST_BOARD                (OBJ_EVENT_GFX_RIVAL_ARVEN + 11)
#define OBJ_EVENT_GFX_STATUE_LEVEL_0             (OBJ_EVENT_GFX_RIVAL_ARVEN + 12)
#define OBJ_EVENT_GFX_STATUE_LEVEL_1             (OBJ_EVENT_GFX_RIVAL_ARVEN + 13)
#define OBJ_EVENT_GFX_STATUE_LEVEL_2             (OBJ_EVENT_GFX_RIVAL_ARVEN + 14)
#define OBJ_EVENT_GFX_STATUE_LEVEL_3             (OBJ_EVENT_GFX_RIVAL_ARVEN + 15)
#define OBJ_EVENT_GFX_ITEM_SILVER_TM             (OBJ_EVENT_GFX_RIVAL_ARVEN + 16)
#define OBJ_EVENT_GFX_ITEM_GOLD_TM               (OBJ_EVENT_GFX_RIVAL_ARVEN + 17)
#define OBJ_EVENT_GFX_ITEM_POKE_BALL             (OBJ_EVENT_GFX_RIVAL_ARVEN + 18)
#define OBJ_EVENT_GFX_ITEM_MEDICINE              (OBJ_EVENT_GFX_RIVAL_ARVEN + 19)
#define OBJ_EVENT_GFX_ITEM_HOLD_ITEM             (OBJ_EVENT_GFX_RIVAL_ARVEN + 20)
#define OBJ_EVENT_GFX_ITEM_MASTER_BALL           (OBJ_EVENT_GFX_RIVAL_ARVEN + 21)
#define OBJ_EVENT_GFX_ITEM_EVO_STONE             (OBJ_EVENT_GFX_RIVAL_ARVEN + 22)
#define OBJ_EVENT_GFX_ITEM_RARE_CANDY            (OBJ_EVENT_GFX_RIVAL_ARVEN + 23)
#define OBJ_EVENT_GFX_ITEM_MINT                  (OBJ_EVENT_GFX_RIVAL_ARVEN + 24)
#define OBJ_EVENT_GFX_ITEM_MEGA_STONE            (OBJ_EVENT_GFX_RIVAL_ARVEN + 25)
#define OBJ_EVENT_GFX_ITEM_Z_CRYSTAL             (OBJ_EVENT_GFX_RIVAL_ARVEN + 26)
#define OBJ_EVENT_GFX_ITEM_DYNAMAX_BALL          (OBJ_EVENT_GFX_RIVAL_ARVEN + 27)
#define OBJ_EVENT_GFX_ITEM_HEALING               (OBJ_EVENT_GFX_RIVAL_ARVEN + 28)
#define OBJ_EVENT_GFX_ITEM_TERA_ORB              (OBJ_EVENT_GFX_RIVAL_ARVEN + 29)
#define OBJ_EVENT_GFX_ITEM_TERA_SHARD            (OBJ_EVENT_GFX_RIVAL_ARVEN + 30)
#define OBJ_EVENT_GFX_GRASS_DEFAULT              (OBJ_EVENT_GFX_RIVAL_ARVEN + 31)
#define OBJ_EVENT_GFX_GOLD_GRASS                 (OBJ_EVENT_GFX_RIVAL_ARVEN + 32)
#define OBJ_EVENT_GFX_FLAG_ADVENTURE             (OBJ_EVENT_GFX_RIVAL_ARVEN + 33)

#define OBJ_EVENT_GFX_DECOR_BED                  (OBJ_EVENT_GFX_FLAG_ADVENTURE + 1)
#define OBJ_EVENT_GFX_DECOR_DRAWERS              (OBJ_EVENT_GFX_FLAG_ADVENTURE + 2)
#define OBJ_EVENT_GFX_DECOR_ROTOM_FAN            (OBJ_EVENT_GFX_FLAG_ADVENTURE + 3)
#define OBJ_EVENT_GFX_DECOR_ROTOM_FROST          (OBJ_EVENT_GFX_FLAG_ADVENTURE + 4)
#define OBJ_EVENT_GFX_DECOR_ROTOM_HEAT           (OBJ_EVENT_GFX_FLAG_ADVENTURE + 5)
#define OBJ_EVENT_GFX_DECOR_ROTOM_MOW            (OBJ_EVENT_GFX_FLAG_ADVENTURE + 6)
#define OBJ_EVENT_GFX_DECOR_ROTOM_WASH           (OBJ_EVENT_GFX_FLAG_ADVENTURE + 7)
#define OBJ_EVENT_GFX_DECOR_WARDROBE             (OBJ_EVENT_GFX_FLAG_ADVENTURE + 8)
#define OBJ_EVENT_GFX_DECOR_CAULDREN             (OBJ_EVENT_GFX_FLAG_ADVENTURE + 9)

#define OBJ_EVENT_GFX_BRENDAN_ALT                (OBJ_EVENT_GFX_DECOR_CAULDREN + 1)
#define OBJ_EVENT_GFX_MAY_ALT                    (OBJ_EVENT_GFX_DECOR_CAULDREN + 2)
#define OBJ_EVENT_GFX_RED_ALT                    (OBJ_EVENT_GFX_DECOR_CAULDREN + 3)
#define OBJ_EVENT_GFX_LEAF_ALT                   (OBJ_EVENT_GFX_DECOR_CAULDREN + 4)
#define OBJ_EVENT_GFX_LYRA_ALT                   (OBJ_EVENT_GFX_DECOR_CAULDREN + 5)
#define OBJ_EVENT_GFX_ETHAN_ALT                  (OBJ_EVENT_GFX_DECOR_CAULDREN + 6)

#define OBJ_EVENT_GFX_GLITCH_KATE                (OBJ_EVENT_GFX_ETHAN_ALT + 1)
#define OBJ_EVENT_GFX_GLITCH_ERMA                (OBJ_EVENT_GFX_ETHAN_ALT + 2)
#define OBJ_EVENT_GFX_GLITCH_RAVEN               (OBJ_EVENT_GFX_ETHAN_ALT + 3)
#define OBJ_EVENT_GFX_GLITCH_TAILS               (OBJ_EVENT_GFX_ETHAN_ALT + 4)
#define OBJ_EVENT_GFX_GLITCH_LS7                 (OBJ_EVENT_GFX_ETHAN_ALT + 5)
#define OBJ_EVENT_GFX_GLITCH_NACHO               (OBJ_EVENT_GFX_ETHAN_ALT + 6)

#define OBJ_EVENT_GFX_RIVAL_RED                  (OBJ_EVENT_GFX_GLITCH_NACHO + 1)
#define OBJ_EVENT_GFX_RIVAL_LEAF                 (OBJ_EVENT_GFX_GLITCH_NACHO + 2)
#define OBJ_EVENT_GFX_RIVAL_ETHAN                (OBJ_EVENT_GFX_GLITCH_NACHO + 3)
#define OBJ_EVENT_GFX_RIVAL_LYRA                 (OBJ_EVENT_GFX_GLITCH_NACHO + 4)
#define OBJ_EVENT_GFX_RIVAL_BRENDAN              (OBJ_EVENT_GFX_GLITCH_NACHO + 5)
#define OBJ_EVENT_GFX_RIVAL_MAY                  (OBJ_EVENT_GFX_GLITCH_NACHO + 6)
#define OBJ_EVENT_GFX_RIVAL_LUCAS                (OBJ_EVENT_GFX_GLITCH_NACHO + 7)
#define OBJ_EVENT_GFX_RIVAL_DAWN                 (OBJ_EVENT_GFX_GLITCH_NACHO + 8)
#define OBJ_EVENT_GFX_RIVAL_HILBERT              (OBJ_EVENT_GFX_GLITCH_NACHO + 9)
#define OBJ_EVENT_GFX_RIVAL_HILDA                (OBJ_EVENT_GFX_GLITCH_NACHO + 10)
#define OBJ_EVENT_GFX_RIVAL_NATE                 (OBJ_EVENT_GFX_GLITCH_NACHO + 11)
#define OBJ_EVENT_GFX_RIVAL_ROSA                 (OBJ_EVENT_GFX_GLITCH_NACHO + 12)
#define OBJ_EVENT_GFX_RIVAL_CALEM                (OBJ_EVENT_GFX_GLITCH_NACHO + 13)
#define OBJ_EVENT_GFX_RIVAL_SERENA               (OBJ_EVENT_GFX_GLITCH_NACHO + 14)
#define OBJ_EVENT_GFX_RIVAL_ELIO                 (OBJ_EVENT_GFX_GLITCH_NACHO + 15)
#define OBJ_EVENT_GFX_RIVAL_SELENE               (OBJ_EVENT_GFX_GLITCH_NACHO + 16)
#define OBJ_EVENT_GFX_RIVAL_VICTOR               (OBJ_EVENT_GFX_GLITCH_NACHO + 17)
#define OBJ_EVENT_GFX_RIVAL_GLORIA               (OBJ_EVENT_GFX_GLITCH_NACHO + 18)
#define OBJ_EVENT_GFX_RIVAL_FLORIAN              (OBJ_EVENT_GFX_GLITCH_NACHO + 19)
#define OBJ_EVENT_GFX_RIVAL_JULIANA              (OBJ_EVENT_GFX_GLITCH_NACHO + 20)

#define OBJ_EVENT_GFX_TEAM_FLARE_GRUNT_F         (OBJ_EVENT_GFX_RIVAL_JULIANA + 1)
#define OBJ_EVENT_GFX_TEAM_FLARE_GRUNT_M         (OBJ_EVENT_GFX_RIVAL_JULIANA + 2)
#define OBJ_EVENT_GFX_TEAM_FLARE_LYSANDER        (OBJ_EVENT_GFX_RIVAL_JULIANA + 3)
#define OBJ_EVENT_GFX_TEAM_GALACTIC_CYRUS        (OBJ_EVENT_GFX_RIVAL_JULIANA + 4)
#define OBJ_EVENT_GFX_TEAM_GALACTIC_GRUNT_F      (OBJ_EVENT_GFX_RIVAL_JULIANA + 5)
#define OBJ_EVENT_GFX_TEAM_GALACTIC_GRUNT_M      (OBJ_EVENT_GFX_RIVAL_JULIANA + 6)
#define OBJ_EVENT_GFX_TEAM_NEO_PLASMA_COLRESS    (OBJ_EVENT_GFX_RIVAL_JULIANA + 7)
#define OBJ_EVENT_GFX_TEAM_NEO_PLASMA_GRUNT_F    (OBJ_EVENT_GFX_RIVAL_JULIANA + 8)
#define OBJ_EVENT_GFX_TEAM_NEO_PLASMA_GRUNT_M    (OBJ_EVENT_GFX_RIVAL_JULIANA + 9)
#define OBJ_EVENT_GFX_TEAM_PLASMA_GHETSIS        (OBJ_EVENT_GFX_RIVAL_JULIANA + 10)
#define OBJ_EVENT_GFX_TEAM_PLASMA_GRUNT_F        (OBJ_EVENT_GFX_RIVAL_JULIANA + 11)
#define OBJ_EVENT_GFX_TEAM_PLASMA_GRUNT_M        (OBJ_EVENT_GFX_RIVAL_JULIANA + 12)
#define OBJ_EVENT_GFX_TEAM_ROCKET_ARCHER         (OBJ_EVENT_GFX_RIVAL_JULIANA + 13)
#define OBJ_EVENT_GFX_TEAM_ROCKET_ARIANA         (OBJ_EVENT_GFX_RIVAL_JULIANA + 14)
#define OBJ_EVENT_GFX_TEAM_ROCKET_PETREL         (OBJ_EVENT_GFX_RIVAL_JULIANA + 15)
#define OBJ_EVENT_GFX_TEAM_ROCKET_PROTON         (OBJ_EVENT_GFX_RIVAL_JULIANA + 16)

#define OBJ_EVENT_GFX_ROUTE_BUG                  (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 1)
#define OBJ_EVENT_GFX_ROUTE_DARK                 (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 2)
#define OBJ_EVENT_GFX_ROUTE_DRAGON               (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 3)
#define OBJ_EVENT_GFX_ROUTE_ELECTRIC             (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 4)
#define OBJ_EVENT_GFX_ROUTE_FAIRY                (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 5)
#define OBJ_EVENT_GFX_ROUTE_FIGHTING             (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 6)
#define OBJ_EVENT_GFX_ROUTE_FIRE                 (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 7)
#define OBJ_EVENT_GFX_ROUTE_FLYING               (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 8)
#define OBJ_EVENT_GFX_ROUTE_GHOST                (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 9)
#define OBJ_EVENT_GFX_ROUTE_GRASS                (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 10)
#define OBJ_EVENT_GFX_ROUTE_GROUND               (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 11)
#define OBJ_EVENT_GFX_ROUTE_ICE                  (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 12)
#define OBJ_EVENT_GFX_ROUTE_MYSTERY              (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 13)
#define OBJ_EVENT_GFX_ROUTE_NORMAL               (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 14)
#define OBJ_EVENT_GFX_ROUTE_POISON               (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 15)
#define OBJ_EVENT_GFX_ROUTE_PSYCHIC              (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 16)
#define OBJ_EVENT_GFX_ROUTE_ROCK                 (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 17)
#define OBJ_EVENT_GFX_ROUTE_STEEL                (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 18)
#define OBJ_EVENT_GFX_ROUTE_WATER                (OBJ_EVENT_GFX_TEAM_ROCKET_PROTON + 19)


#define OBJ_EVENT_GFX_FOLLOW_MON_PARTNER         (OBJ_EVENT_GFX_ROUTE_WATER + 1)
#define OBJ_EVENT_GFX_FOLLOW_MON_0               (OBJ_EVENT_GFX_ROUTE_WATER + 2)
#define OBJ_EVENT_GFX_FOLLOW_MON_1               (OBJ_EVENT_GFX_ROUTE_WATER + 3)
#define OBJ_EVENT_GFX_FOLLOW_MON_2               (OBJ_EVENT_GFX_ROUTE_WATER + 4)
#define OBJ_EVENT_GFX_FOLLOW_MON_3               (OBJ_EVENT_GFX_ROUTE_WATER + 5)
#define OBJ_EVENT_GFX_FOLLOW_MON_4               (OBJ_EVENT_GFX_ROUTE_WATER + 6)
#define OBJ_EVENT_GFX_FOLLOW_MON_5               (OBJ_EVENT_GFX_ROUTE_WATER + 7)

#define OBJ_EVENT_GFX_FOLLOW_MON_PAL_10         OBJ_EVENT_GFX_FOLLOW_MON_4
#define OBJ_EVENT_GFX_FOLLOW_MON_PAL_1          OBJ_EVENT_GFX_FOLLOW_MON_5

#define OBJ_EVENT_GFX_FOLLOW_MON_FIRST           OBJ_EVENT_GFX_FOLLOW_MON_PARTNER
#define OBJ_EVENT_GFX_FOLLOW_MON_LAST            OBJ_EVENT_GFX_FOLLOW_MON_5

#define NUM_OBJ_EVENT_GFX                        (OBJ_EVENT_GFX_FOLLOW_MON_LAST + 1)

#define OBJ_EVENT_GFX_PLAYER_AVATAR             (0xFF00)
#define OBJ_EVENT_GFX_PLAYER_RIVAL              (0xFF01)

#define OBJ_EVENT_GFX_MP_FOLLOW_MON             OBJ_EVENT_GFX_FOLLOW_MON_3

// Player gfx objects
//
#define PLAYER_OBJ_GFX_BRENDAN_NORMAL           0
#define PLAYER_OBJ_GFX_BRENDAN_FIELD_MOVE       1
#define PLAYER_OBJ_GFX_BRENDAN_RIDING           2
#define PLAYER_OBJ_GFX_MAY_NORMAL               3
#define PLAYER_OBJ_GFX_MAY_FIELD_MOVE           4
#define PLAYER_OBJ_GFX_MAY_RIDING               5

#define PLAYER_OBJ_GFX_RED_NORMAL               (PLAYER_OBJ_GFX_MAY_RIDING + 1)
#define PLAYER_OBJ_GFX_RED_FIELD_MOVE           (PLAYER_OBJ_GFX_MAY_RIDING + 2)
#define PLAYER_OBJ_GFX_RED_RIDING               (PLAYER_OBJ_GFX_MAY_RIDING + 3)
#define PLAYER_OBJ_GFX_LEAF_NORMAL              (PLAYER_OBJ_GFX_MAY_RIDING + 4)
#define PLAYER_OBJ_GFX_LEAF_FIELD_MOVE          (PLAYER_OBJ_GFX_MAY_RIDING + 5)
#define PLAYER_OBJ_GFX_LEAF_RIDING              (PLAYER_OBJ_GFX_MAY_RIDING + 6)

#define PLAYER_OBJ_GFX_ETHAN_NORMAL             (PLAYER_OBJ_GFX_LEAF_RIDING + 1)
#define PLAYER_OBJ_GFX_ETHAN_FIELD_MOVE         (PLAYER_OBJ_GFX_LEAF_RIDING + 2)
#define PLAYER_OBJ_GFX_ETHAN_RIDING             (PLAYER_OBJ_GFX_LEAF_RIDING + 3)
#define PLAYER_OBJ_GFX_LYRA_NORMAL              (PLAYER_OBJ_GFX_LEAF_RIDING + 4)
#define PLAYER_OBJ_GFX_LYRA_FIELD_MOVE          (PLAYER_OBJ_GFX_LEAF_RIDING + 5)
#define PLAYER_OBJ_GFX_LYRA_RIDING              (PLAYER_OBJ_GFX_LEAF_RIDING + 6)

#define PLAYER_OBJ_GFX_FIRST                    PLAYER_OBJ_GFX_BRENDAN_NORMAL
#define PLAYER_OBJ_GFX_LAST                     PLAYER_OBJ_GFX_LYRA_RIDING

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

// Special object event local ids
#define OBJ_EVENT_ID_PLAYER             255
#define OBJ_EVENT_ID_FOLLOWER           254
#define OBJ_EVENT_ID_CAMERA             127

// IDs for dynamic object event spawns
#define OBJ_EVENT_ID_FOLLOW_MON_FIRST   230
#define OBJ_EVENT_ID_FOLLOW_MON_LAST    240

// IDs for dynamic multiplayer objects
#define OBJ_EVENT_ID_MULTIPLAYER_FIRST  241
#define OBJ_EVENT_ID_MULTIPLAYER_LAST   244
#define OBJ_EVENT_ID_MULTIPLAYER_COUNT  (OBJ_EVENT_ID_MULTIPLAYER_LAST - OBJ_EVENT_ID_MULTIPLAYER_FIRST + 1)

// Object event local ids referenced in C files
#define LOCALID_ROUTE111_PLAYER_FALLING 45
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_FARAWAY_ISLAND_MEW 1
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9
#define LOCALID_BATTLE_TOWER_LOBBY_REPORTER 5
#define LOCALID_TRUCK_BOX_TOP 1
#define LOCALID_TRUCK_BOX_BOTTOM_L 2
#define LOCALID_TRUCK_BOX_BOTTOM_R 3
#define LOCALID_OLDALE_MART_CLERK 1
#define LOCALID_LAVARIDGE_MART_CLERK 1
#define LOCALID_FALLARBOR_MART_CLERK 1
#define LOCALID_VERDANTURF_MART_CLERK 1
#define LOCALID_PETALBURG_MART_CLERK 1
#define LOCALID_SLATEPORT_MART_CLERK 1
#define LOCALID_MAUVILLE_MART_CLERK 1
#define LOCALID_RUSTBORO_MART_CLERK 1
#define LOCALID_FORTREE_MART_CLERK 1
#define LOCALID_MOSSDEEP_MART_CLERK 1
#define LOCALID_SOOTOPOLIS_MART_CLERK 1
#define LOCALID_BATTLE_FRONTIER_MART_CLERK 1
#define LOCALID_SLATEPORT_ENERGY_GURU 25

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
