#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_VanillaMaps
#define MAP_INSIDE_OF_TRUCK               (0 | (0 << 8))
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (1 | (0 << 8))
#define MAP_SAFARI_ZONE_NORTHWEST         (2 | (0 << 8))
#define MAP_SAFARI_ZONE_NORTH             (3 | (0 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST         (4 | (0 << 8))
#define MAP_SAFARI_ZONE_SOUTH             (5 | (0 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE        (6 | (0 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST         (7 | (0 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST         (8 | (0 << 8))

// gMapGroup_RogueHub
#define MAP_ROGUE_MANAGER                   (0 | (1 << 8))
#define MAP_ROGUE_HUB                       (1 | (1 << 8))
#define MAP_ROGUE_HUB_TRANSITION            (2 | (1 << 8))
#define MAP_ROGUE_HUB_PROF_LAB              (3 | (1 << 8))
#define MAP_ROGUE_HUB_INTERIOR_CONFIG_ROOM  (4 | (1 << 8))
#define MAP_ROGUE_HUB_INTERIOR_CLOTHES_SHOP (5 | (1 << 8))
#define MAP_ROGUE_HUB_POKEMON_CENTRE        (6 | (1 << 8))
#define MAP_ROGUE_HUB_ADVENTURE_ENTERANCE   (7 | (1 << 8))
#define MAP_ROGUE_HUB_BAKERY                (8 | (1 << 8))
#define MAP_ROGUE_HUB_DEBUG                 (9 | (1 << 8))

// gMapGroup_RogueHubTiles
#define MAP_ROGUE_TILE_TEST1              (0 | (2 << 8))
#define MAP_ROGUE_TILE_TEST2              (1 | (2 << 8))
#define MAP_ROGUE_TILE_TEST3              (2 | (2 << 8))
#define MAP_ROGUE_TILE_ADVENTURE_ENTRANCE (3 | (2 << 8))
#define MAP_ROGUE_TILE_EMPTY              (4 | (2 << 8))
#define MAP_ROGUE_TILE_MART               (5 | (2 << 8))
#define MAP_ROGUE_TILE_SAFARI_ENTRANCE    (6 | (2 << 8))
#define MAP_ROGUE_TILE_OUTDOOR_MART       (7 | (2 << 8))
#define MAP_ROGUE_TILE_BERRY_PATCH1       (8 | (2 << 8))

// gMapGroup_RogueRun
#define MAP_ROGUE_ADVENTURE_PATHS          (0 | (3 << 8))
#define MAP_ROGUE_ROUTE_FIELD0             (1 | (3 << 8))
#define MAP_ROGUE_ROUTE_FIELD1             (2 | (3 << 8))
#define MAP_ROGUE_ROUTE_FOREST0            (3 | (3 << 8))
#define MAP_ROGUE_ROUTE_FOREST1            (4 | (3 << 8))
#define MAP_ROGUE_ROUTE_CAVE0              (5 | (3 << 8))
#define MAP_ROGUE_ROUTE_MOUNTAIN0          (6 | (3 << 8))
#define MAP_ROGUE_ROUTE_MOUNTAIN1          (7 | (3 << 8))
#define MAP_ROGUE_ROUTE_MOUNTAIN2          (8 | (3 << 8))
#define MAP_ROGUE_ROUTE_MOUNTAIN3          (9 | (3 << 8))
#define MAP_ROGUE_ROUTE_WATER_FRONT0       (10 | (3 << 8))
#define MAP_ROGUE_ROUTE_WATER_FRONT1       (11 | (3 << 8))
#define MAP_ROGUE_ROUTE_URBAN0             (12 | (3 << 8))
#define MAP_ROGUE_ROUTE_URBAN1             (13 | (3 << 8))
#define MAP_ROGUE_ROUTE_KANTO_FIELD0       (14 | (3 << 8))
#define MAP_ROGUE_ROUTE_KANTO_MOUNTAIN0    (15 | (3 << 8))
#define MAP_ROGUE_ROUTE_KANTO_URBAN0       (16 | (3 << 8))
#define MAP_ROGUE_ROUTE_KANTO_URBAN1       (17 | (3 << 8))
#define MAP_ROGUE_ROUTE_KANTO_FOREST0      (18 | (3 << 8))
#define MAP_ROGUE_ROUTE_KANTO_CAVE0        (19 | (3 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_FIELD0       (20 | (3 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_FIELD1       (21 | (3 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_CAVE0        (22 | (3 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_WATER_FRONT0 (23 | (3 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_URBAN0       (24 | (3 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_MOUNTAIN0    (25 | (3 << 8))
#define MAP_ROGUE_ROUTE_CHAOS0             (26 | (3 << 8))

// gMapGroup_RogueAdventureEncounters
#define MAP_ROGUE_ENCOUNTER_REST_STOP (0 | (4 << 8))
#define MAP_ROGUE_ENCOUNTER_HEALING   (1 | (4 << 8))
#define MAP_ROGUE_ENCOUNTER_SHOPS     (2 | (4 << 8))
#define MAP_ROGUE_ENCOUNTER_TUTORS    (3 | (4 << 8))
#define MAP_ROGUE_ENCOUNTER_MINI_BOSS (4 | (4 << 8))
#define MAP_ROGUE_ENCOUNTER_DEN       (5 | (4 << 8))
#define MAP_ROGUE_ENCOUNTER_GAME_SHOW (6 | (4 << 8))
#define MAP_ROGUE_ENCOUNTER_GRAVEYARD (7 | (4 << 8))
#define MAP_ROGUE_ENCOUNTER_LAB       (8 | (4 << 8))
#define MAP_ROGUE_BOSS_0              (9 | (4 << 8))
#define MAP_ROGUE_BOSS_8              (10 | (4 << 8))
#define MAP_ROGUE_BOSS_9              (11 | (4 << 8))
#define MAP_ROGUE_BOSS_10             (12 | (4 << 8))
#define MAP_ROGUE_BOSS_11             (13 | (4 << 8))
#define MAP_ROGUE_BOSS_12             (14 | (4 << 8))
#define MAP_ROGUE_BOSS_13             (15 | (4 << 8))

// gMapGroup_RogueAdventureMonEncounters
#define MAP_ROGUE_SOUTHERN_ISLAND_LATIOS   (0 | (5 << 8))
#define MAP_ROGUE_SOUTHERN_ISLAND_LATIAS   (1 | (5 << 8))
#define MAP_ROGUE_SPECIAL_ARTICUNO         (2 | (5 << 8))
#define MAP_ROGUE_SPECIAL_ZAPDOS           (3 | (5 << 8))
#define MAP_ROGUE_SPECIAL_MOLTRES          (4 | (5 << 8))
#define MAP_ROGUE_SPECIAL_MEWTWO           (5 | (5 << 8))
#define MAP_ROGUE_SPECIAL_MEW              (6 | (5 << 8))
#define MAP_ROGUE_SPECIAL_RAIKOU           (7 | (5 << 8))
#define MAP_ROGUE_SPECIAL_ENTEI            (8 | (5 << 8))
#define MAP_ROGUE_SPECIAL_SUICUNE          (9 | (5 << 8))
#define MAP_ROGUE_SPECIAL_HOOH             (10 | (5 << 8))
#define MAP_ROGUE_SPECIAL_LUGIA            (11 | (5 << 8))
#define MAP_ROGUE_SPECIAL_CELEBI           (12 | (5 << 8))
#define MAP_ROGUE_SPECIAL_REGI             (13 | (5 << 8))
#define MAP_ROGUE_SPECIAL_KYOGRE           (14 | (5 << 8))
#define MAP_ROGUE_SPECIAL_GROUDON          (15 | (5 << 8))
#define MAP_ROGUE_SPECIAL_RAYQUAZA         (16 | (5 << 8))
#define MAP_ROGUE_SPECIAL_JIRACHI          (17 | (5 << 8))
#define MAP_ROGUE_SPECIAL_DEOXYS           (18 | (5 << 8))
#define MAP_ROGUE_SPECIAL_GENERIC_WILD_MON (19 | (5 << 8))
#define MAP_ROGUE_SPECIAL_GEN4_MON         (20 | (5 << 8))
#define MAP_ROGUE_SPECIAL_GEN5_MON         (21 | (5 << 8))
#define MAP_ROGUE_SPECIAL_GEN6_MON         (22 | (5 << 8))
#define MAP_ROGUE_SPECIAL_GEN7_MON         (23 | (5 << 8))
#define MAP_ROGUE_SPECIAL_GEN8_MON         (24 | (5 << 8))

#define MAP_GROUPS_COUNT 6

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
