#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_VanillaMaps
#define MAP_INSIDE_OF_TRUCK               (0 | (0 << 8))
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (1 | (0 << 8))
#define MAP_SAFARI_ZONE_NORTHWEST         (2 | (0 << 8))
#define MAP_SAFARI_ZONE_NORTH             (3 | (0 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST         (4 | (0 << 8))
#define MAP_SAFARI_ZONE_SOUTH             (5 | (0 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE        (6 | (0 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST         (7 | (0 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST         (8 | (0 << 8))

// gMapGroup_RogueHub
#define MAP_ROGUE_MANAGER                   (0 | (1 << 8))
#define MAP_ROGUE_HUB                       (1 | (1 << 8))
#define MAP_ROGUE_HUB_TRANSITION            (2 | (1 << 8))
#define MAP_ROGUE_HUB_PROF_LAB              (3 | (1 << 8))
#define MAP_ROGUE_HUB_INTERIOR_CONFIG_ROOM  (4 | (1 << 8))
#define MAP_ROGUE_HUB_INTERIOR_CLOTHES_SHOP (5 | (1 << 8))
#define MAP_ROGUE_HUB_POKEMON_CENTRE        (6 | (1 << 8))
#define MAP_ROGUE_HUB_ADVENTURE_ENTERANCE   (7 | (1 << 8))
#define MAP_ROGUE_HUB_BAKERY                (8 | (1 << 8))
#define MAP_ROGUE_HUB_DEBUG                 (9 | (1 << 8))
#define MAP_ROGUE_INTRO                     (10 | (1 << 8))

// gMapGroup_RogueHubAreas
#define MAP_ROGUE_HALLWAY_FACADE_HORIZONTAL (0 | (2 << 8))
#define MAP_ROGUE_HALLWAY_FACADE_VERTICAL   (1 | (2 << 8))
#define MAP_ROGUE_AREA_LABS                 (2 | (2 << 8))
#define MAP_ROGUE_AREA_HOME                 (3 | (2 << 8))
#define MAP_ROGUE_AREA_FARMING_FIELD        (4 | (2 << 8))
#define MAP_ROGUE_AREA_ADVENTURE_ENTRANCE   (5 | (2 << 8))
#define MAP_ROGUE_AREA_SAFARI_ZONE          (6 | (2 << 8))
#define MAP_ROGUE_AREA_SAFARI_ZONE_TUTORIAL (7 | (2 << 8))
#define MAP_ROGUE_AREA_RIDE_TRAINING        (8 | (2 << 8))
#define MAP_ROGUE_AREA_MARTS                (9 | (2 << 8))
#define MAP_ROGUE_AREA_TOWN_SQUARE          (10 | (2 << 8))
#define MAP_ROGUE_AREA_CHALLENGE_FRONTIER   (11 | (2 << 8))
#define MAP_ROGUE_AREA_DAY_CARE             (12 | (2 << 8))
#define MAP_ROGUE_AREA_MARKET               (13 | (2 << 8))

// gMapGroup_RogueHubInteriors
#define MAP_ROGUE_INTERIOR_HOME               (0 | (3 << 8))
#define MAP_ROGUE_INTERIOR_HOME_UPPER         (1 | (3 << 8))
#define MAP_ROGUE_INTERIOR_PROF_LAB           (2 | (3 << 8))
#define MAP_ROGUE_INTERIOR_CONFIG_LAB         (3 | (3 << 8))
#define MAP_ROGUE_INTERIOR_POKE_CONNECT       (4 | (3 << 8))
#define MAP_ROGUE_INTERIOR_SAFARI_CAVE        (5 | (3 << 8))
#define MAP_ROGUE_INTERIOR_RESTAURANT         (6 | (3 << 8))
#define MAP_ROGUE_INTERIOR_CAFE               (7 | (3 << 8))
#define MAP_ROGUE_INTERIOR_SCHOOL             (8 | (3 << 8))
#define MAP_ROGUE_INTERIOR_CHALLENGE_FRONTIER (9 | (3 << 8))
#define MAP_ROGUE_INTERIOR_BILLS_LAB          (10 | (3 << 8))

// gMapGroup_RogueHubTemplates
#define MAP_ROGUE_TEMPLATE_HOMES         (0 | (4 << 8))
#define MAP_ROGUE_TEMPLATE_HOME_BASE     (1 | (4 << 8))
#define MAP_ROGUE_TEMPLATE_HOME_FLOWERS  (2 | (4 << 8))
#define MAP_ROGUE_TEMPLATE_HOME_GRASS    (3 | (4 << 8))
#define MAP_ROGUE_TEMPLATE_HOME_INTERIOR (4 | (4 << 8))

// gMapGroup_RogueHubTesting
#define MAP_ROGUE_TILE_TEST1              (0 | (5 << 8))
#define MAP_ROGUE_TILE_TEST2              (1 | (5 << 8))
#define MAP_ROGUE_TILE_TEST3              (2 | (5 << 8))
#define MAP_ROGUE_TILE_ADVENTURE_ENTRANCE (3 | (5 << 8))
#define MAP_ROGUE_TILE_EMPTY              (4 | (5 << 8))
#define MAP_ROGUE_TILE_MART               (5 | (5 << 8))
#define MAP_ROGUE_TILE_SAFARI_ENTRANCE    (6 | (5 << 8))
#define MAP_ROGUE_TILE_OUTDOOR_MART       (7 | (5 << 8))
#define MAP_ROGUE_TILE_BERRY_PATCH1       (8 | (5 << 8))

// gMapGroup_RogueRun
#define MAP_ROGUE_ADVENTURE_PATHS            (0 | (6 << 8))
#define MAP_ROGUE_ROUTE_FIELD0               (1 | (6 << 8))
#define MAP_ROGUE_ROUTE_FIELD1               (2 | (6 << 8))
#define MAP_ROGUE_ROUTE_FOREST0              (3 | (6 << 8))
#define MAP_ROGUE_ROUTE_FOREST1              (4 | (6 << 8))
#define MAP_ROGUE_ROUTE_CAVE0                (5 | (6 << 8))
#define MAP_ROGUE_ROUTE_MOUNTAIN0            (6 | (6 << 8))
#define MAP_ROGUE_ROUTE_MOUNTAIN1            (7 | (6 << 8))
#define MAP_ROGUE_ROUTE_MOUNTAIN2            (8 | (6 << 8))
#define MAP_ROGUE_ROUTE_MOUNTAIN3            (9 | (6 << 8))
#define MAP_ROGUE_ROUTE_WATER_FRONT0         (10 | (6 << 8))
#define MAP_ROGUE_ROUTE_WATER_FRONT1         (11 | (6 << 8))
#define MAP_ROGUE_ROUTE_URBAN0               (12 | (6 << 8))
#define MAP_ROGUE_ROUTE_URBAN1               (13 | (6 << 8))
#define MAP_ROGUE_ROUTE_KANTO_FIELD0         (14 | (6 << 8))
#define MAP_ROGUE_ROUTE_KANTO_MOUNTAIN0      (15 | (6 << 8))
#define MAP_ROGUE_ROUTE_KANTO_URBAN0         (16 | (6 << 8))
#define MAP_ROGUE_ROUTE_KANTO_URBAN1         (17 | (6 << 8))
#define MAP_ROGUE_ROUTE_KANTO_FOREST0        (18 | (6 << 8))
#define MAP_ROGUE_ROUTE_KANTO_CAVE0          (19 | (6 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_FIELD0         (20 | (6 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_FIELD1         (21 | (6 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_CAVE0          (22 | (6 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_WATER_FRONT0   (23 | (6 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_URBAN0         (24 | (6 << 8))
#define MAP_ROGUE_ROUTE_JOHTO_MOUNTAIN0      (25 | (6 << 8))
#define MAP_ROGUE_ROUTE_CHAOS0               (26 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_205           (27 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_ETERNA_FOREST (28 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_207           (29 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_215           (30 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_212           (31 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_217           (32 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_210           (33 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_201           (34 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_214           (35 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_209           (36 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_MT_CORONET    (37 | (6 << 8))
#define MAP_ROGUE_ROUTE_SINNOH_IRON_ISLAND   (38 | (6 << 8))

// gMapGroup_RogueAdventureEncounters
#define MAP_ROGUE_ENCOUNTER_REST_STOP        (0 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_HEALING          (1 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_SHOPS            (2 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_TUTORS           (3 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_DAY_CARE         (4 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_MINI_BOSS        (5 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_DEN              (6 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_GAME_SHOW        (7 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_GRAVEYARD        (8 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_LAB              (9 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_HONEY_TREE       (10 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_SHRINE           (11 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_CATCHING_CONTEST (12 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_SIGN             (13 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_BATTLE_SIM       (14 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_ROCKET_HIDEOUT   (15 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_SILPH_CO         (16 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_MT_CHIMNEY       (17 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_MAGMA_HIDEOUT    (18 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_AQUA_HIDEOUT     (19 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_SEAFLOOR_CAVERN  (20 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_LAKE_VALOR       (21 | (7 << 8))
#define MAP_ROGUE_ENCOUNTER_GALACTIC_HQ      (22 | (7 << 8))
#define MAP_ROGUE_BOSS_0                     (23 | (7 << 8))
#define MAP_ROGUE_BOSS_8                     (24 | (7 << 8))
#define MAP_ROGUE_BOSS_9                     (25 | (7 << 8))
#define MAP_ROGUE_BOSS_10                    (26 | (7 << 8))
#define MAP_ROGUE_BOSS_11                    (27 | (7 << 8))
#define MAP_ROGUE_BOSS_12                    (28 | (7 << 8))
#define MAP_ROGUE_BOSS_13                    (29 | (7 << 8))
#define MAP_ROGUE_BOSS_FINAL                 (30 | (7 << 8))
#define MAP_ROGUE_BOSS_VICTORY_LAP           (31 | (7 << 8))

// gMapGroup_RogueAdventureMonEncounters
#define MAP_ROGUE_SOUTHERN_ISLAND_LATIOS   (0 | (8 << 8))
#define MAP_ROGUE_SOUTHERN_ISLAND_LATIAS   (1 | (8 << 8))
#define MAP_ROGUE_SPECIAL_ARTICUNO         (2 | (8 << 8))
#define MAP_ROGUE_SPECIAL_ZAPDOS           (3 | (8 << 8))
#define MAP_ROGUE_SPECIAL_MOLTRES          (4 | (8 << 8))
#define MAP_ROGUE_SPECIAL_MEWTWO           (5 | (8 << 8))
#define MAP_ROGUE_SPECIAL_MEW              (6 | (8 << 8))
#define MAP_ROGUE_SPECIAL_RAIKOU           (7 | (8 << 8))
#define MAP_ROGUE_SPECIAL_ENTEI            (8 | (8 << 8))
#define MAP_ROGUE_SPECIAL_SUICUNE          (9 | (8 << 8))
#define MAP_ROGUE_SPECIAL_HOOH             (10 | (8 << 8))
#define MAP_ROGUE_SPECIAL_LUGIA            (11 | (8 << 8))
#define MAP_ROGUE_SPECIAL_CELEBI           (12 | (8 << 8))
#define MAP_ROGUE_SPECIAL_REGI             (13 | (8 << 8))
#define MAP_ROGUE_SPECIAL_KYOGRE           (14 | (8 << 8))
#define MAP_ROGUE_SPECIAL_GROUDON          (15 | (8 << 8))
#define MAP_ROGUE_SPECIAL_RAYQUAZA         (16 | (8 << 8))
#define MAP_ROGUE_SPECIAL_JIRACHI          (17 | (8 << 8))
#define MAP_ROGUE_SPECIAL_DEOXYS           (18 | (8 << 8))
#define MAP_ROGUE_SPECIAL_LAKE_GUARDIAN    (19 | (8 << 8))
#define MAP_ROGUE_SPECIAL_ARCEUS           (20 | (8 << 8))
#define MAP_ROGUE_SPECIAL_GENERIC_WILD_MON (21 | (8 << 8))
#define MAP_ROGUE_SPECIAL_GEN4_MON         (22 | (8 << 8))
#define MAP_ROGUE_SPECIAL_GEN5_MON         (23 | (8 << 8))
#define MAP_ROGUE_SPECIAL_GEN6_MON         (24 | (8 << 8))
#define MAP_ROGUE_SPECIAL_GEN7_MON         (25 | (8 << 8))
#define MAP_ROGUE_SPECIAL_GEN8_MON         (26 | (8 << 8))
#define MAP_ROGUE_SPECIAL_GEN9_MON         (27 | (8 << 8))

#define MAP_GROUPS_COUNT 9

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
