
// Areas
//
#define HUB_AREA_HOME   0
#define HUB_AREA_COUNT  1

#define HUB_AREA_NONE 255

// Upgrades
//

#define HUB_UPGRADE_FIRST                   0

#define HUB_UPGRADE_HOME_LOWER_FLOOR        (HUB_UPGRADE_FIRST + 0)
#define HUB_UPGRADE_HOME_UPPER_FLOOR        (HUB_UPGRADE_FIRST + 1)
#define HUB_UPGRADE_HOME_BERRY_FIELD1       (HUB_UPGRADE_FIRST + 2)
#define HUB_UPGRADE_HOME_BERRY_FIELD2       (HUB_UPGRADE_FIRST + 3)
#define HUB_UPGRADE_HOME_GRASS_FIELD        (HUB_UPGRADE_FIRST + 4)
#define HUB_UPGRADE_HOME_GRASS_FIELD_SHED   (HUB_UPGRADE_FIRST + 5)

#define HUB_UPGRADE_COUNT                   (HUB_UPGRADE_HOME_GRASS_FIELD_SHED + 1)

#define HUB_UPGRADE_NONE 255

// Misc
//
#define HUB_UPGRADE_MAX_REQUIREMENTS 2
#define MAX_HUB_UPGRADE_TREES_PER_AREA 8

