
// Areas
//
#define HUB_AREA_FIRST                   0

#define HUB_AREA_LABS                   (HUB_AREA_FIRST + 0)
#define HUB_AREA_ADVENTURE_ENTRANCE     (HUB_AREA_FIRST + 1)
#define HUB_AREA_HOME                   (HUB_AREA_FIRST + 2)
#define HUB_AREA_BERRY_FIELD            (HUB_AREA_FIRST + 3)
#define HUB_AREA_SAFARI_ZONE            (HUB_AREA_FIRST + 4)
#define HUB_AREA_RIDE_TRAINING          (HUB_AREA_FIRST + 5)
#define HUB_AREA_MARTS                  (HUB_AREA_FIRST + 6)
#define HUB_AREA_TOWN_SQUARE            (HUB_AREA_FIRST + 7)
#define HUB_AREA_CHALLENGE_FRONTIER     (HUB_AREA_FIRST + 8)
#define HUB_AREA_DAY_CARE               (HUB_AREA_FIRST + 9)

#define HUB_AREA_COUNT                  (HUB_AREA_DAY_CARE + 1)

#define HUB_AREA_NONE 255

// Upgrades
//

#define HUB_UPGRADE_FIRST                               0

#define HUB_UPGRADE_HOME_LOWER_FLOOR                    (HUB_UPGRADE_FIRST + 0)
#define HUB_UPGRADE_HOME_UPPER_FLOOR                    (HUB_UPGRADE_FIRST + 1)

#define HUB_UPGRADE_BERRY_FIELD_EXTRA_FIELD0            (HUB_UPGRADE_FIRST + 2)
#define HUB_UPGRADE_BERRY_FIELD_EXTRA_FIELD1            (HUB_UPGRADE_FIRST + 3)
#define HUB_UPGRADE_BERRY_FIELD_EXTRA_FIELD2            (HUB_UPGRADE_FIRST + 4)
#define HUB_UPGRADE_BERRY_FIELD_HIGHER_YEILD0           (HUB_UPGRADE_FIRST + 5)
#define HUB_UPGRADE_BERRY_FIELD_HIGHER_YEILD1           (HUB_UPGRADE_FIRST + 6)
#define HUB_UPGRADE_BERRY_FIELD_HIGHER_YEILD2           (HUB_UPGRADE_FIRST + 7)

#define HUB_UPGRADE_ADVENTURE_ENTRANCE_RANDOM_STARTER   (HUB_UPGRADE_FIRST + 8)
#define HUB_UPGRADE_ADVENTURE_ENTRANCE_ADVENTURE_REPLAY (HUB_UPGRADE_FIRST + 9)

#define HUB_UPGRADE_SAFARI_ZONE_LEGENDS_CAVE            (HUB_UPGRADE_FIRST + 10)

#define HUB_UPGRADE_COUNT                               (HUB_UPGRADE_SAFARI_ZONE_LEGENDS_CAVE + 1)

// NOTE - Once the next update is out ALWAYS add the upgrades at the bottom of this list

#define HUB_UPGRADE_NONE 255

// Player Home Options
//
#define HOME_AREA_STYLE_OVERGROWN       0
#define HOME_AREA_STYLE_FLOWERS         1
#define HOME_AREA_STYLE_PLAIN           2
#define HOME_AREA_STYLE_COUNT           3

#define HOME_BUILDING_STYLE_CAVE        0
#define HOME_BUILDING_STYLE_TREES       1
#define HOME_BUILDING_STYLE_RED_BRICK   2
#define HOME_BUILDING_STYLE_WOODEN      3
#define HOME_BUILDING_STYLE_GYM         4
#define HOME_BUILDING_STYLE_COUNT       5

#define HOME_REGION_HOUSE               0 // this is first as it overlaps the others, so is the highest priority
#define HOME_REGION_PLACEABLE_REGION    1
#define HOME_REGION_COUNT               2

#define HOME_DECOR_OUTSIDE_ENV_COUNT    128
#define HOME_DECOR_OUTSIDE_PROP_COUNT   32
#define HOME_DECOR_LOWER_PROP_COUNT     16
#define HOME_DECOR_UPPER_PROP_COUNT     16
#define HOME_DECOR_TOTAL_COUNT          (HOME_DECOR_OUTSIDE_ENV_COUNT + HOME_DECOR_OUTSIDE_PROP_COUNT + HOME_DECOR_LOWER_PROP_COUNT + HOME_DECOR_UPPER_PROP_COUNT)

#define HOME_DECOR_CODE_NO_ROOM         255
#define HOME_DECOR_CODE_NOT_HERE        254

#define HOME_DECOR_OUTSIDE_ENV_OFFSET   0
#define HOME_DECOR_OUTSIDE_PROP_OFFSET  (HOME_DECOR_OUTSIDE_ENV_COUNT)
#define HOME_DECOR_LOWER_PROP_OFFSET    (HOME_DECOR_OUTSIDE_ENV_COUNT + HOME_DECOR_OUTSIDE_PROP_COUNT)
#define HOME_DECOR_UPPER_PROP_OFFSET    (HOME_DECOR_OUTSIDE_ENV_COUNT + HOME_DECOR_OUTSIDE_PROP_COUNT + HOME_DECOR_LOWER_PROP_COUNT)

#define HOME_DECOR_ENV_POND_2x2         0
#define HOME_DECOR_ENV_POND_3x3         1
#define HOME_DECOR_ENV_POND_4x4         2
#define HOME_DECOR_ENV_POND_5x5         3
#define HOME_DECOR_ENV_MOUNTAIN_2x2     4
#define HOME_DECOR_ENV_MOUNTAIN_3x3     5
#define HOME_DECOR_ENV_MOUNTAIN_4x4     6
#define HOME_DECOR_ENV_MOUNTAIN_5x5     7
#define HOME_DECOR_ENV_GRASS_PATH_2x2   8
#define HOME_DECOR_ENV_GRASS_PATH_3x3   9
#define HOME_DECOR_ENV_GRASS_PATH_4x4   10
#define HOME_DECOR_ENV_GRASS_PATH_5x5   11
#define HOME_DECOR_ENV_COUNT            12

#define HOME_DECOR_PROP_ 0 // todo

// Misc
//
#define HUB_UPGRADE_MAX_REQUIREMENTS 2
#define MAX_HUB_UPGRADE_TREES_PER_AREA 8

#define HUB_AREA_CONN_SOUTH 0
#define HUB_AREA_CONN_NORTH 1
#define HUB_AREA_CONN_WEST  2
#define HUB_AREA_CONN_EAST  3
#define HUB_AREA_CONN_COUNT 4

#define HUB_AREA_CONN_TELEPORT 5

#define HUB_AREA_CONN_NONE 255