Sandbox_Trainer_Derp::
	trainerbattle_single TRAINER_VIEWIER_DERP, Sandbox_Trainer_Derp_Text_0, Sandbox_Trainer_Derp_Text_1
	msgbox Sandbox_Trainer_Derp_Text_2, MSGBOX_AUTOCLOSE
	return


Sandbox_Trainer_Mawile::
	trainerbattle_single TRAINER_VIEWIER_MAWILE, Sandbox_Trainer_Mawile_Text_0, Sandbox_Trainer_Mawile_Text_1
	msgbox Sandbox_Trainer_Mawile_Text_2, MSGBOX_AUTOCLOSE
	return


Sandbox_Trainer_Greez::
	trainerbattle_single TRAINER_VIEWIER_GREEZ, Sandbox_Trainer_Greez_Text_0, Sandbox_Trainer_Greez_Text_1
	msgbox Sandbox_Trainer_Greez_Text_2, MSGBOX_AUTOCLOSE
	return


Sandbox_Trainer_Dolphin::
	trainerbattle_single TRAINER_VIEWIER_DOLPHIN, Sandbox_Trainer_Dolphin_Text_0, Sandbox_Trainer_Dolphin_Text_1
	msgbox Sandbox_Trainer_Dolphin_Text_2, MSGBOX_AUTOCLOSE
	return


Sandbox_Trainer_Derp_Text_0:
	.string "Fancy seeing you here Conner.\p"
	.string "Going to awaken RAYQUAZA?\p"
	.string "NOT ON MY WATCH!$"

Sandbox_Trainer_Derp_Text_1:
	.string "Seems I’ve been defeated by the\n"
	.string "Legendary LaterManner.\p"
	.string "Now...\p"
	.string "Go win this.\n"
	.string "You deserve it, champ$"

Sandbox_Trainer_Derp_Text_2:
	.string "DERPSTER: Go win this.\n"
	.string "You deserve it, champ$"

Sandbox_Trainer_Mawile_Text_0:
	.string "You thought I was a grunt, but it was I,\n"
	.string "MAWEELAY!$"

Sandbox_Trainer_Mawile_Text_1:
	.string "Why couldn't you do that to Blue?$"

Sandbox_Trainer_Mawile_Text_2:
	.string "MAWEELAY: Why couldn't you do that to\n"
	.string "Blue?$"

Sandbox_Trainer_Greez_Text_0:
	.string "I was about to stal- I mean see the\n"
	.string "female grunt.\p"
	.string "Wanna battle?$"

Sandbox_Trainer_Greez_Text_1:
	.string "But like... The female grunt tho.$"

Sandbox_Trainer_Greez_Text_2:
	.string "GREEZ: But like... The female grunt tho.$"

Sandbox_Trainer_Dolphin_Text_0:
	.string "I swear I can solve this puzzle first\n"
	.string "try!$"

Sandbox_Trainer_Dolphin_Text_1:
	.string "I failed the puzzle…$"

Sandbox_Trainer_Dolphin_Text_2:
	.string "DOLPHIN: I failed the puzzle…$"
