Sandbox_Trainer_Derp::
	trainerbattle_single TRAINER_VIEWIER_DERP, Sandbox_Trainer_Derp_Text_0, Sandbox_Trainer_Derp_Text_1
	msgbox Sandbox_Trainer_Derp_Text_2, MSGBOX_AUTOCLOSE
	return


Sandbox_Trainer_Derp_Text_0:
	.string "DERPSTER: Fancy seeing you here\n"
	.string "Conner.\p"
	.string "Going to awaken RAYQUAZA?\p"
	.string "NOT ON MY WATCH!$"

Sandbox_Trainer_Derp_Text_1:
	.string "Seems I’ve been defeated by the\n"
	.string "Legendary LaterManner.\p"
	.string "Now...\p"
	.string "Go win this.\n"
	.string "You deserve it, champ$"

Sandbox_Trainer_Derp_Text_2:
	.string "DERPSTER: Go win this.\n"
	.string "You deserve it, champ$"
