BattleDome_Text_Potential1::
	.string "The best candidate to be a champ!$"

BattleDome_Text_Potential2::
	.string "A sure-finalist team.$"

BattleDome_Text_Potential3::
	.string "A likely top-three finisher.$"

BattleDome_Text_Potential4::
	.string "A candidate to finish first.$"

BattleDome_Text_Potential5::
	.string "A team with top-class potential.$"

BattleDome_Text_Potential6::
	.string "The dark horse team this tournament.$"

BattleDome_Text_Potential7::
	.string "A better-than-average team.$"

BattleDome_Text_Potential8::
	.string "This tournament's average team.$"

BattleDome_Text_Potential9::
	.string "A team with average potential.$"

BattleDome_Text_Potential10::
	.string "A weaker-than-average team.$"

BattleDome_Text_Potential11::
	.string "A team looking for its first win.$"

BattleDome_Text_Potential12::
	.string "One win will make this team proud.$"

BattleDome_Text_Potential13::
	.string "Overall, a weak team.$"

BattleDome_Text_Potential14::
	.string "A team with very low potential.$"

BattleDome_Text_Potential15::
	.string "A team unlikely to win the tournament.$"

BattleDome_Text_Potential16::
	.string "The team most unlikely to win.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "The perfect, invincible superstar!$"

BattleDome_Text_StyleRiskDisaster::
	.string "Willing to risk total disaster at times.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Skilled at enduring long battles.$"

BattleDome_Text_StyleVariesTactics::
	.string "Varies tactics to suit the opponent.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Has a tough winning pattern.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "Occasionally uses a very rare move.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Uses startling and disruptive moves.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Constantly watches HP in battle.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Good at storing then loosing power.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Skilled at enfeebling foes.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Prefers tactics that rely on luck.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Attacks with a regal atmosphere.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Attacks with powerful, low-PP moves.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Skilled at enfeebling, then attacking.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Battles while enduring all attacks.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Skilled at upsetting foes emotionally.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Uses strong and straightforward moves.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Aggressively uses strong moves.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Battles while cleverly dodging attacks.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Skilled at using upsetting attacks.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Uses many popular moves.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Has moves for powerful combinations.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Uses high-probability attacks.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Aggressively uses spectacular moves.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Emphasizes offense over defense.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Emphasizes defense over offense.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Attacks quickly with strong moves.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Often uses moves with added effects.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Uses a well-balanced mix of moves.$"

BattleDome_Text_StyleSampleMessage1::
	.string "This is sample message 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "This is sample message 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "This is sample message 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "This is sample message 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Emphasizes HP and ATTACK.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Emphasizes HP and DEFENSE.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Emphasizes HP and SPEED.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Emphasizes HP and SP. ATTACK.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Emphasizes HP and SP. DEFENSE.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Emphasizes ATTACK and DEFENSE.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Emphasizes ATTACK and SPEED.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Emphasizes ATTACK and SP. ATTACK.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Emphasizes ATTACK and SP. DEFENSE.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Emphasizes DEFENSE and SPEED.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Emphasizes DEFENSE and SP. ATTACK.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Emphasizes DEFENSE and SP. DEFENSE.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Emphasizes SPEED and SP. ATTACK.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Emphasizes SPEED and SP. DEFENSE.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Emphasizes SP. ATTACK and SP. DEFENSE.$"

BattleDome_Text_EmphasizesHP::
	.string "Emphasizes HP.$"

BattleDome_Text_EmphasizesAtk::
	.string "Emphasizes ATTACK.$"

BattleDome_Text_EmphasizesDef::
	.string "Emphasizes DEFENSE.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Emphasizes SPEED.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Emphasizes SP. ATTACK.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Emphasizes SP. DEFENSE.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Neglects HP and ATTACK.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Neglects HP and DEFENSE.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Neglects HP and SPEED.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Neglects HP and SP. ATTACK.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Neglects HP and SP. DEFENSE.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Neglects ATTACK and DEFENSE.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Neglects ATTACK and SPEED.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Neglects ATTACK and SP. ATTACK.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Neglects ATTACK and SP. DEFENSE.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Neglects DEFENSE and SPEED.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Neglects DEFENSE and SP. ATTACK.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Neglects DEFENSE and SP. DEFENSE.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Neglects SPEED and SP. ATTACK.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Neglects SPEED and SP. DEFENSE.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Neglects SP. ATTACK and SP. DEFENSE.$"

BattleDome_Text_NeglectsHP::
	.string "Neglects HP.$"

BattleDome_Text_NeglectsAtk::
	.string "Neglects ATTACK.$"

BattleDome_Text_NeglectsDef::
	.string "Neglects DEFENSE.$"

BattleDome_Text_NeglectsSpeed::
	.string "Neglects SPEED.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Neglects SP. ATTACK.$"

BattleDome_Text_NeglectsSpDef::
	.string "Neglects SP. DEFENSE.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Raises POKéMON in a well-balanced way.$"

BattleDome_Text_LetTheBattleBegin::
	.string "Let the battle begin!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} won using {STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} became the champ!$"

BattleDome_Text_TrainerWonByDefault::
	.string "{STR_VAR_1} won by default!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} won outright by default!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} won without using a move!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} won outright with no moves!$"


BattlePyramid_Text_ExitHintUp1::
	.string "-"

BattlePyramid_Text_ExitHintLeft1::
	.string "-"

BattlePyramid_Text_ExitHintRight1::
	.string "-"

BattlePyramid_Text_ExitHintDown1::
	.string "-"

BattlePyramid_Text_ZeroItemsRemaining1::
	.string "-"

BattlePyramid_Text_OneItemRemaining1::
	.string "-"

BattlePyramid_Text_TwoItemsRemaining1::
	.string "-"

BattlePyramid_Text_ThreeItemsRemaining1::
	.string "-"

BattlePyramid_Text_FourItemsRemaining1::
	.string "-"

BattlePyramid_Text_FiveItemsRemaining1::
	.string "-"

BattlePyramid_Text_SixItemsRemaining1::
	.string "-"

BattlePyramid_Text_SevenItemsRemaining1::
	.string "-"

BattlePyramid_Text_EightItemsRemaining1::
	.string "-"

BattlePyramid_Text_ZeroTrainersRemaining1::
	.string "-"

BattlePyramid_Text_OneTrainersRemaining1::
	.string "-"

BattlePyramid_Text_TwoTrainersRemaining1::
	.string "-"

BattlePyramid_Text_ThreeTrainersRemaining1::
	.string "-"

BattlePyramid_Text_FourTrainersRemaining1::
	.string "-"

BattlePyramid_Text_FiveTrainersRemaining1::
	.string "-"

BattlePyramid_Text_SixTrainersRemaining1::
	.string "-"

BattlePyramid_Text_SevenTrainersRemaining1::
	.string "-"

BattlePyramid_Text_ExitHintUp2::
	.string "-"

BattlePyramid_Text_ExitHintLeft2::
	.string "-"

BattlePyramid_Text_ExitHintRight2::
	.string "-"

BattlePyramid_Text_ExitHintDown2::
	.string "-"

BattlePyramid_Text_ZeroItemsRemaining2::
	.string "-"

BattlePyramid_Text_OneItemRemaining2::
	.string "-"

BattlePyramid_Text_TwoItemsRemaining2::
	.string "-"

BattlePyramid_Text_ThreeItemsRemaining2::
	.string "-"

BattlePyramid_Text_FourItemsRemaining2::
	.string "-"

BattlePyramid_Text_FiveItemsRemaining2::
	.string "-"

BattlePyramid_Text_SixItemsRemaining2::
	.string "-"

BattlePyramid_Text_SevenItemsRemaining2::
	.string "-"

BattlePyramid_Text_EightItemsRemaining2::
	.string "-"

BattlePyramid_Text_ZeroTrainersRemaining2::
	.string "-"

BattlePyramid_Text_OneTrainersRemaining2::
	.string "-"

BattlePyramid_Text_TwoTrainersRemaining2::
	.string "-"

BattlePyramid_Text_ThreeTrainersRemaining2::
	.string "-"

BattlePyramid_Text_FourTrainersRemaining2::
	.string "-"

BattlePyramid_Text_FiveTrainersRemaining2::
	.string "-"

BattlePyramid_Text_SixTrainersRemaining2::
	.string "-"

BattlePyramid_Text_SevenTrainersRemaining2::
	.string "-"

BattlePyramid_Text_ExitHintUp3::
	.string "-"

BattlePyramid_Text_ExitHintLeft3::
	.string "-"

BattlePyramid_Text_ExitHintRight3::
	.string "-"

BattlePyramid_Text_ExitHintDown3::
	.string "-"

BattlePyramid_Text_ZeroItemsRemaining3::
	.string "-"

BattlePyramid_Text_OneItemRemaining3::
	.string "-"

BattlePyramid_Text_TwoItemsRemaining3::
	.string "-"

BattlePyramid_Text_ThreeItemsRemaining3::
	.string "-"

BattlePyramid_Text_FourItemsRemaining3::
	.string "-"

BattlePyramid_Text_FiveItemsRemaining3::
	.string "-"

BattlePyramid_Text_SixItemsRemaining3::
	.string "-"

BattlePyramid_Text_SevenItemsRemaining3::
	.string "-"

BattlePyramid_Text_EightItemsRemaining3::
	.string "-"

BattlePyramid_Text_ZeroTrainersRemaining3::
	.string "-"

BattlePyramid_Text_OneTrainersRemaining3::
	.string "-"

BattlePyramid_Text_TwoTrainersRemaining3::
	.string "-"

BattlePyramid_Text_ThreeTrainersRemaining3::
	.string "-"

BattlePyramid_Text_FourTrainersRemaining3::
	.string "-"

BattlePyramid_Text_FiveTrainersRemaining3::
	.string "-"

BattlePyramid_Text_SixTrainersRemaining3::
	.string "-"

BattlePyramid_Text_SevenTrainersRemaining3::
	.string "-"

BattlePyramid_Text_ExitHintUp4::
	.string "-"

BattlePyramid_Text_ExitHintLeft4::
	.string "-"

BattlePyramid_Text_ExitHintRight4::
	.string "-"

BattlePyramid_Text_ExitHintDown4::
	.string "-"

BattlePyramid_Text_ZeroItemsRemaining4::
	.string "-"

BattlePyramid_Text_OneItemRemaining4::
	.string "-"

BattlePyramid_Text_TwoItemsRemaining4::
	.string "-"

BattlePyramid_Text_ThreeItemsRemaining4::
	.string "-"

BattlePyramid_Text_FourItemsRemaining4::
	.string "-"

BattlePyramid_Text_FiveItemsRemaining4::
	.string "-"

BattlePyramid_Text_SixItemsRemaining4::
	.string "-"

BattlePyramid_Text_SevenItemsRemaining4::
	.string "-"

BattlePyramid_Text_EightItemsRemaining4::
	.string "-"

BattlePyramid_Text_ZeroTrainersRemaining4::
	.string "-"

BattlePyramid_Text_OneTrainersRemaining4::
	.string "-"

BattlePyramid_Text_TwoTrainersRemaining4::
	.string "-"

BattlePyramid_Text_ThreeTrainersRemaining4::
	.string "-"

BattlePyramid_Text_FourTrainersRemaining4::
	.string "-"

BattlePyramid_Text_FiveTrainersRemaining4::
	.string "-"

BattlePyramid_Text_SixTrainersRemaining4::
	.string "-"

BattlePyramid_Text_SevenTrainersRemaining4::
	.string "-"

BattlePyramid_Text_ExitHintUp5::
	.string "-"

BattlePyramid_Text_ExitHintLeft5::
	.string "-"

BattlePyramid_Text_ExitHintRight5::
	.string "-"

BattlePyramid_Text_ExitHintDown5::
	.string "-"

BattlePyramid_Text_ZeroItemsRemaining5::
	.string "-"

BattlePyramid_Text_OneItemRemaining5::
	.string "-"

BattlePyramid_Text_TwoItemsRemaining5::
	.string "-"

BattlePyramid_Text_ThreeItemsRemaining5::
	.string "-"

BattlePyramid_Text_FourItemsRemaining5::
	.string "-"

BattlePyramid_Text_FiveItemsRemaining5::
	.string "-"

BattlePyramid_Text_SixItemsRemaining5::
	.string "-"

BattlePyramid_Text_SevenItemsRemaining5::
	.string "-"

BattlePyramid_Text_EightItemsRemaining5::
	.string "-"

BattlePyramid_Text_ZeroTrainersRemaining5::
	.string "-"

BattlePyramid_Text_OneTrainersRemaining5::
	.string "-"

BattlePyramid_Text_TwoTrainersRemaining5::
	.string "-"

BattlePyramid_Text_ThreeTrainersRemaining5::
	.string "-"

BattlePyramid_Text_FourTrainersRemaining5::
	.string "-"

BattlePyramid_Text_FiveTrainersRemaining5::
	.string "-"

BattlePyramid_Text_SixTrainersRemaining5::
	.string "-"

BattlePyramid_Text_SevenTrainersRemaining5::
	.string "-"

BattlePyramid_Text_ExitHintUp6::
	.string "-"

BattlePyramid_Text_ExitHintLeft6::
	.string "-"

BattlePyramid_Text_ExitHintRight6::
	.string "-"

BattlePyramid_Text_ExitHintDown6::
	.string "-"

BattlePyramid_Text_ZeroItemsRemaining6::
	.string "-"

BattlePyramid_Text_OneItemRemaining6::
	.string "-"

BattlePyramid_Text_TwoItemsRemaining6::
	.string "-"

BattlePyramid_Text_ThreeItemsRemaining6::
	.string "-"

BattlePyramid_Text_FourItemsRemaining6::
	.string "-"

BattlePyramid_Text_FiveItemsRemaining6::
	.string "-"

BattlePyramid_Text_SixItemsRemaining6::
	.string "-"

BattlePyramid_Text_SevenItemsRemaining6::
	.string "-"

BattlePyramid_Text_EightItemsRemaining6::
	.string "-"

BattlePyramid_Text_ZeroTrainersRemaining6::
	.string "-"

BattlePyramid_Text_OneTrainersRemaining6::
	.string "-"

BattlePyramid_Text_TwoTrainersRemaining6::
	.string "-"

BattlePyramid_Text_ThreeTrainersRemaining6::
	.string "-"

BattlePyramid_Text_FourTrainersRemaining6::
	.string "-"

BattlePyramid_Text_FiveTrainersRemaining6::
	.string "-"

BattlePyramid_Text_SixTrainersRemaining6::
	.string "-"

BattlePyramid_Text_SevenTrainersRemaining6::
	.string "-"

gText_YourPartnerHasRetired::
	.string "-"

BattleFrontier_Lounge2_Text_SalonMaidenIsThere::
	.string "-"

BattleFrontier_Lounge2_Text_SalonMaidenSilverMons::
	.string "-"

BattleFrontier_Lounge2_Text_SalonMaidenGoldMons::
	.string "-"

BattleFrontier_Lounge2_Text_DoubleBattleAdvice1::
	.string "-"

BattleFrontier_Lounge2_Text_DoubleBattleAdvice2::
	.string "-"

BattleFrontier_Lounge2_Text_DoubleBattleAdvice3::
	.string "-"

BattleFrontier_Lounge2_Text_MultiBattleAdvice::
	.string "-"

BattleFrontier_Lounge2_Text_LinkMultiBattleAdvice::
	.string "-"

BattleFrontier_Lounge2_Text_DomeAceIsThere::
	.string "-"

BattleFrontier_Lounge2_Text_DomeAceSilverMons::
	.string "-"

BattleFrontier_Lounge2_Text_DomeAceGoldMons::
	.string "-"

BattleFrontier_Lounge2_Text_FactoryHeadIsThere::
	.string "-"

BattleFrontier_Lounge2_Text_FactoryHeadSilverMons::
	.string "-"

BattleFrontier_Lounge2_Text_FactoryHeadGoldMons::
	.string "-"

BattleFrontier_Lounge2_Text_PalaceMavenIsThere::
	.string "-"

BattleFrontier_Lounge2_Text_PalaceMavenSilverMons::
	.string "-"

BattleFrontier_Lounge2_Text_PalaceMavenGoldMons::
	.string "-"

BattleFrontier_Lounge2_Text_ArenaTycoonIsThere::
	.string "-"

BattleFrontier_Lounge2_Text_ArenaTycoonSilverMons::
	.string "-"

BattleFrontier_Lounge2_Text_ArenaTycoonGoldMons::
	.string "-"

BattleFrontier_Lounge2_Text_PikeQueenIsThere::
	.string "-"

BattleFrontier_Lounge2_Text_PikeQueenSilverMons::
	.string "-"

BattleFrontier_Lounge2_Text_PikeQueenGoldMons::
	.string "-"

BattleFrontier_Lounge2_Text_PyramidKingIsThere::
	.string "-"

BattleFrontier_Lounge2_Text_PyramidKingSilverMons::
	.string "-"

BattleFrontier_Lounge2_Text_PyramidKingGoldMons::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlHardy::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlLonely::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlBrave::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlAdamant::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlNaughty::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlBold::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlDocileNaiveQuietQuirky::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlRelaxed::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlImpish::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlLax::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlTimid::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlHasty::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlSerious::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlJolly::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlModest::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlMild::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlBashful::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlRash::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlCalm::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlGentle::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlSassy::
	.string "-"

BattleFrontier_Lounge5_Text_NatureGirlCareful::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerSingle::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerDouble::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerMulti::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattleDomeSingle::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattleDomeDouble::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattleFactorySingle::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattleFactoryDouble::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattlePalaceSingle::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattlePalaceDouble::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattleArena::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattlePike::
	.string "-"

BattleFrontier_Lounge3_Text_ChallengeBattlePyramid::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattleTowerSingle::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattleTowerDouble::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattleTowerMulti::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattleDomeSingle::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattleDomeDouble::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattleFactorySingle::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattleFactoryDouble::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattlePalaceSingle::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattlePalaceDouble::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattleArena::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattlePike::
	.string "-"

BattleFrontier_Lounge3_Text_GetToBattlePyramid::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_KissPosterDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_KissCushionDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_SmoochumDollDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_TogepiDollDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_MeowthDollDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_ClefairyDollDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_DittoDollDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_CyndaquilDollDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_ChikoritaDollDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_TotodileDollDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_LargeDollDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_ProteinDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_CalciumDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_IronDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_ZincDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_CarbosDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_HPUpDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_LeftoversDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_WhiteHerbDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_QuickClawDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_MentalHerbDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_BrightpowderDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_ChoiceBandDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_KingsRockDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_FocusBandDesc::
	.string "-"

BattleFrontier_ExchangeServiceCorner_Text_ScopeLensDesc::
	.string "-"

BattleFrontier_Lounge7_Text_SoftboiledDesc::
	.string "-"

BattleFrontier_Lounge7_Text_SeismicTossDesc::
	.string "-"

BattleFrontier_Lounge7_Text_DreamEaterDesc::
	.string "-"

BattleFrontier_Lounge7_Text_MegaPunchDesc::
	.string "-"

BattleFrontier_Lounge7_Text_MegaKickDesc::
	.string "-"

BattleFrontier_Lounge7_Text_BodySlamDesc::
	.string "-"

BattleFrontier_Lounge7_Text_RockSlideDesc::
	.string "-"

BattleFrontier_Lounge7_Text_CounterDesc::
	.string "-"

BattleFrontier_Lounge7_Text_ThunderWaveDesc::
	.string "-"

BattleFrontier_Lounge7_Text_SwordsDanceDesc::
	.string "-"

BattleFrontier_Lounge7_Text_DefenseCurlDesc::
	.string "-"

BattleFrontier_Lounge7_Text_SnoreDesc::
	.string "-"

BattleFrontier_Lounge7_Text_MudSlapDesc::
	.string "-"

BattleFrontier_Lounge7_Text_SwiftDesc::
	.string "-"

BattleFrontier_Lounge7_Text_IcyWindDesc::
	.string "-"

BattleFrontier_Lounge7_Text_EndureDesc::
	.string "-"

BattleFrontier_Lounge7_Text_PsychUpDesc::
	.string "-"

BattleFrontier_Lounge7_Text_IcePunchDesc::
	.string "-"

BattleFrontier_Lounge7_Text_ThunderPunchDesc::
	.string "-"

BattleFrontier_Lounge7_Text_FirePunchDesc::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice1Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice1Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice1Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice1Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice1Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice2Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice2Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice2Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice2Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice2Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice3Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice3Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice3Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice3Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice3Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice4Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice4Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice4Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice4Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice4Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice5Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice5Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice5Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice5Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice5Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice6Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice6Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice6Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice6Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice6Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice7Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice7Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice7Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice7Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice7Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice8Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice8Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice8Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice8Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice8Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice9Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice9Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice9Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice9Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice9Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice10Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice10Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice10Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice10Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice10Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice11Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice11Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice11Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice11Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice11Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice12Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice12Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice12Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice12Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice12Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice13Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice13Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice13Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice13Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice13Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice14Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice14Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice14Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice14Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice14Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice15Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice15Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice15Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice15Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice15Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice16Intro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice16Mon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice16Mon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice16Accept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_Apprentice16Reject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_LassIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_LassMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_LassMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_LassAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_LassReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_YoungsterIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_YoungsterMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_YoungsterMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_YoungsterAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_YoungsterReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_HikerIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_HikerMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_HikerMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_HikerAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_HikerReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BeautyIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BeautyMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BeautyMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BeautyAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BeautyReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_FishermanIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_FishermanMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_FishermanMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_FishermanAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_FishermanReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_LadyIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_LadyMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_LadyMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_LadyAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_LadyReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CyclingTriathleteFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CyclingTriathleteFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CyclingTriathleteFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CyclingTriathleteFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CyclingTriathleteFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BugCatcherIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BugCatcherMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BugCatcherMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BugCatcherAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BugCatcherReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SchoolKidMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SchoolKidMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SchoolKidMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SchoolKidMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SchoolKidMReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RichBoyIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RichBoyMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RichBoyMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RichBoyAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RichBoyReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BlackBeltIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BlackBeltMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BlackBeltMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BlackBeltAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BlackBeltReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_TuberFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_TuberFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_TuberFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_TuberFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_TuberFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_HexManiacIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_HexManiacMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_HexManiacMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_HexManiacAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_HexManiacReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnBreederMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnBreederMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnBreederMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnBreederMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnBreederMReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RunningTriathleteFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RunningTriathleteFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RunningTriathleteFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RunningTriathleteFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RunningTriathleteFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RunningTriathleteMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RunningTriathleteMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RunningTriathleteMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RunningTriathleteMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RunningTriathleteMReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BattleGirlIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BattleGirlMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BattleGirlMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BattleGirlAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BattleGirlReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CyclingTriathleteMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CyclingTriathleteMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CyclingTriathleteMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CyclingTriathleteMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CyclingTriathleteMReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_TuberMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_TuberMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_TuberMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_TuberMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_TuberMReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_GuitaristIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_GuitaristMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_GuitaristMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_GuitaristAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_GuitaristReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_GentlemanIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_GentlemanMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_GentlemanMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_GentlemanAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_GentlemanReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokefanMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokefanMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokefanMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokefanMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokefanMReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ExpertMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ExpertMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ExpertMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ExpertMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ExpertMReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ExpertFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ExpertFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ExpertFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ExpertFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ExpertFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_DragonTamerIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_DragonTamerMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_DragonTamerMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_DragonTamerAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_DragonTamerReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BirdKeeperIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BirdKeeperMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BirdKeeperMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BirdKeeperAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BirdKeeperReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_NinjaBoyIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_NinjaBoyMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_NinjaBoyMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_NinjaBoyAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_NinjaBoyReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ParasolLadyIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ParasolLadyMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ParasolLadyMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ParasolLadyAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_ParasolLadyReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BugManiacIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BugManiacMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BugManiacMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BugManiacAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_BugManiacReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SailorIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SailorMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SailorMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SailorAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SailorReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CollectorIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CollectorMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CollectorMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CollectorAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CollectorReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnRangerMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnRangerMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnRangerMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnRangerMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnRangerMReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnRangerFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnRangerFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnRangerFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnRangerFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnRangerFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_AromaLadyIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_AromaLadyMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_AromaLadyMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_AromaLadyAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_AromaLadyReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RuinManiacIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RuinManiacMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RuinManiacMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RuinManiacAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_RuinManiacReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CoolTrainerMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CoolTrainerMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CoolTrainerMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CoolTrainerMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CoolTrainerMReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CoolTrainerFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CoolTrainerFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CoolTrainerFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CoolTrainerFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CoolTrainerFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokemaniacIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokemaniacMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokemaniacMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokemaniacAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokemaniacReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_KindlerIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_KindlerMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_KindlerMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_KindlerAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_KindlerReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CamperIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CamperMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CamperMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CamperAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_CamperReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PicnickerIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PicnickerMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PicnickerMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PicnickerAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PicnickerReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PsychicMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PsychicMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PsychicMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PsychicMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PsychicMReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PsychicFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PsychicFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PsychicFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PsychicFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PsychicFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SchoolKidFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SchoolKidFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SchoolKidFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SchoolKidFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SchoolKidFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnBreederFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnBreederFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnBreederFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnBreederFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PkmnBreederFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokefanFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokefanFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokefanFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokefanFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_PokefanFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmerFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmerFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmerFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmerFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmerFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmingTriathleteMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmingTriathleteMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmingTriathleteMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmingTriathleteMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmingTriathleteMReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmingTriathleteFIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmingTriathleteFMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmingTriathleteFMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmingTriathleteFAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmingTriathleteFReject::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmerMIntro::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmerMMon1::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmerMMon2Ask::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmerMAccept::
	.string "-"

BattleFrontier_BattleTowerMultiPartnerRoom_Text_SwimmerMReject::
	.string "-"

BattleFrontier_BattleArenaLobby_Text_RulesAreListed::
	.string "-"

BattleFrontier_BattleArenaLobby_Text_ReadWhichHeading::
	.string "-"

BattleFrontier_BattleArenaLobby_Text_ExplainBattleRules::
	.string "-"

BattleFrontier_BattleArenaLobby_Text_ExplainMindRules::
	.string "-"

BattleFrontier_BattleArenaLobby_Text_ExplainSkillRules::
	.string "-"

BattleFrontier_BattleArenaLobby_Text_ExplainBodyRules::
	.string "-"

BattleFrontier_BattleArenaBattleRoom_Text_SetKOTourneyBegin::
	.string "-"

BattleFrontier_BattleArenaBattleRoom_EventScript_DoArenaBattle::
	.string "-"

BattleFrontier_BattleArenaBattleRoom_Text_WinnerIsOpponent::
	.string "-"

BattleFrontier_BattleArenaBattleRoom_Text_WinnerIsPlayer::
	.string "-"

BattleFrontier_BattleArenaBattleRoom_Text_MonsWillBeRestored::
	.string "-"

BattleFrontier_BattleArenaBattleRoom_Text_SaveAndShutDown::
	.string "-"

BattleFrontier_BattleArenaBattleRoom_Text_RetireFromChallenge::
	.string "-"

BattleFrontier_BattleArenaBattleRoom_Text_ReadyFor2ndOpponent::
	.string "-"

BattleFrontier_BattleArenaBattleRoom_Text_ReadyFor3rdOpponent::
	.string "-"

BattleFrontier_BattleArenaBattleRoom_Text_SavingPleaseWait::
	.string "-"

BattleFrontier_BattlePalaceLobby_Text_FailedToSaveBeforeEndingChallenge::
	.string "-"

BattleFrontier_BattleDomeLobby_Text_ReceivedPrize::
	.string "-"

BattleFrontier_BattlePalaceLobby_Text_NoSpaceForPrize::
	.string "-"

BattleFrontier_BattlePalaceLobby_Text_WeHaveBeenWaiting::
	.string "-"

BattleFrontier_BattlePalaceLobby_Text_MustSaveBeforeChallenge::
	.string "-"

BattleFrontier_BattlePalaceLobby_Text_ReadWhichHeading::
	.string "-"

BattleFrontier_BattlePalaceLobby_Text_ExplainRulesBasics::
	.string "-"

BattleFrontier_BattlePalaceLobby_Text_ExplainRulesNature::
	.string "-"

BattleFrontier_BattlePalaceLobby_Text_ExplainRulesMoves::
	.string "-"

BattleFrontier_BattlePalaceLobby_Text_ExplainRulesUnderpowered::
	.string "-"

BattleFrontier_BattlePalaceLobby_Text_ExplainRulesWhenInDanger::
	.string "-"

BattleFrontier_BattlePalaceBattleRoom_EventScript_DoPalaceBattle::
	.string "-"

BattleFrontier_BattlePalaceBattleRoom_Text_LetMeRestoreYourMons::
	.string "-"

BattleFrontier_BattlePalaceBattleRoom_Text_SaveAndQuitGame::
	.string "-"

BattleFrontier_BattlePalaceBattleRoom_Text_WishToQuitChallenge::
	.string "-"

BattleFrontier_BattlePalaceBattleRoom_Text_SavingData::
	.string "-"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor2ndOpponent::
	.string "-"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor3rdOpponent::
	.string "-"

BattleFrontier_BattleTowerLobby_Text_ReceivedPrize::
	.string "-"

BattleFrontier_BattleFactoryLobby_Text_RulesAreListed::
	.string "-"

BattleFrontier_BattleFactoryLobby_Text_ReadWhichHeading::
	.string "-"

BattleFrontier_BattleFactoryPreBattleRoom_Text_HoldMonsChooseFromSelection::
	.string "-"

BattleFrontier_BattleFactoryPreBattleRoom_Text_RightThisWay::
	.string "-"

BattleFrontier_BattleFactoryPreBattleRoom_Text_LetUsRestoreMons::
	.string "-"

BattleFrontier_BattleFactoryPreBattleRoom_Text_SaveAndQuitGame::
	.string "-"

BattleFrontier_BattleFactoryPreBattleRoom_Text_RetireFromChallenge::
	.string "-"

BattleFrontier_BattleFactoryPreBattleRoom_Text_LikeToSwapMon::
	.string "-"

BattleFrontier_BattleFactoryPreBattleRoom_Text_YourSwapIsComplete::
	.string "-"

BattleFrontier_BattleFactoryPreBattleRoom_Text_ReadyFor2ndOpponent::
	.string "-"

BattleFrontier_BattleFactoryPreBattleRoom_Text_ReadyFor3rdOpponent::
	.string "-"

BattleFrontier_BattleFactoryPreBattleRoom_Text_SavingDataPleaseWait::
	.string "-"

BattleFrontier_BattlePike_EventScript_Retire::
	.string "-"

BattleFacility_TrainerBattle_PlaceholderText::
	.string "-"

BattleFrontier_BattleTowerBattleRoom_Text_RecordCouldntBeSaved::
	.string "-"

gText_LinkStandby3::
	.string "Link standby…$"

gText_BattlePyramidConfirmRest::
	.string "-"

gText_BattlePyramidConfirmRetire::
	.string "-"



BattleDome_Text_Round1Match1::
	.string "Round 1, Match 1$"

BattleDome_Text_Round1Match2::
	.string "Round 1, Match 2$"

BattleDome_Text_Round1Match3::
	.string "Round 1, Match 3$"

BattleDome_Text_Round1Match4::
	.string "Round 1, Match 4$"

BattleDome_Text_Round1Match5::
	.string "Round 1, Match 5$"

BattleDome_Text_Round1Match6::
	.string "Round 1, Match 6$"

BattleDome_Text_Round1Match7::
	.string "Round 1, Match 7$"

BattleDome_Text_Round1Match8::
	.string "Round 1, Match 8$"

BattleDome_Text_Round2Match1::
	.string "Round 2, Match 1$"

BattleDome_Text_Round2Match2::
	.string "Round 2, Match 2$"

BattleDome_Text_Round2Match3::
	.string "Round 2, Match 3$"

BattleDome_Text_Round2Match4::
	.string "Round 2, Match 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Semifinal Match 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Semifinal Match 2$"

BattleDome_Text_FinalMatch::
	.string "Final Match$"
