gText_Birch_Welcome::
	.string "Hello!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Welcome to POKéMON EMERALD ROGUE!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "In this game, every time you embark \n"
	.string "on an Adventure...\p"
	.string "the world and the POKéMON you\n"
	.string "encounter will be different!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now...\n"
	.string "Time to tell me about yourself$"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Pick a style$"

gText_Birch_WhatsYourName::
	.string "Now, what is your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "{PLAYER}{KUN}!"
	.string "$"

gText_Birch_AreYouReady::
	.string "I'll be waiting for you in my LAB!\p"
	.string "Come and find me once you arrive.\p"
	.string "$"
