gText_Birch_Welcome::
	.string "Wah!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "TODO\n"
	.string "o.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "How do you want to preset?$"

gText_Birch_BoyOrGirl::
	.string "Which do you prefer?$"

gText_Birch_WhatsYourName::
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "{PLAYER}{KUN}!"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "$"
