LilycoveCity_EventScript_DefeatedMay2::
	msgbox LilycoveCity_EventScript_DefeatedMay2_Text_0
	giveitem ITEM_AMULET_COIN
	return


LilycoveCity_EventScript_DefeatedBrendan2::
	msgbox LilycoveCity_EventScript_DefeatedBrendan2_Text_0
	giveitem ITEM_AMULET_COIN
	return


LilycoveCity_EventScript_DefeatedMay2_Text_0:
	.string "MAY: Wow you keep just getting\n"
	.string "stronger and stronger {PLAYER}{KUN}!\p"
	.string "Oh wait one second.\p"
	.string "I was suppose to give you this before\n"
	.string "we fought…\p"
	.string "My bad…$"

LilycoveCity_EventScript_DefeatedBrendan2_Text_0:
	.string "BRENDAN: Wow you keep just getting\n"
	.string "stronger and stronger {PLAYER}{KUN}!\p"
	.string "Oh wait one second.\p"
	.string "I was suppose to give you this before\n"
	.string "we fought…\p"
	.string "My bad…$"
