// == WARNING ==
// DO NOT EDIT THIS FILE
// This file was automatically generated by PokemonDataGenerator
//

static const struct RideMonInfo sRideMonInfo[NUM_SPECIES] = 
{
    [SPECIES_VENUSAUR] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-2,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-10, .playerY=-3,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_CHARIZARD] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-3,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-4,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_BLASTOISE] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-8, .playerY=-6,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_PIDGEOT] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-6, .playerY=-8,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_FEAROW] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-10,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-12,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-6, .playerY=-10,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_ARBOK] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-4,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_NIDOQUEEN] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-2,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-3,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-7, .playerY=-4,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_NIDOKING] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-3,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-3,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-6, .playerY=-3,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_PARASECT] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-5,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_DUGTRIO] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=0,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=0,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-5,
                .monX=4, .monY=0,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_PRIMEAPE] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-6, .playerY=-5,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_ARCANINE] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-9,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-1,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-1, .playerY=-6,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_POLIWRATH] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-6,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_ALAKAZAM] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-4,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_MACHAMP] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-6,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_VICTREEBEL] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-5,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_TENTACRUEL] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-7,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_GOLEM] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-5,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_RAPIDASH] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-2, .playerY=-6,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_SLOWBRO] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-4,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_DODRIO] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-5,
                .monX=1, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_DEWGONG] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-1, .playerY=-5,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_MUK] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-3,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-3,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-6, .playerY=-4,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_ONIX] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-9,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-9,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-9,
                .monX=7, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_ELECTRODE] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-8,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-6,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_WEEZING] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-6, .playerY=-5,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_RHYDON] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-5,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_KANGASKHAN] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-3,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_SEAKING] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-6,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_STARMIE] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-5,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_TAUROS] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-11,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-1, .playerY=-6,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_GYARADOS] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-11,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-11,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-11,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_LAPRAS] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-5,
                .monX=8, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_AERODACTYL] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-8,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_SNORLAX] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-8,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-6, .playerY=-8,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_ARTICUNO] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-7,
                .monX=5, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_ZAPDOS] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-8,
                .monX=7, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_MOLTRES] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-8,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-8,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_DRAGONITE] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-7,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_MEGANIUM] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-6,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_TYPHLOSION] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-7, .playerY=-5,
                .monX=5, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_FERALIGATR] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-7,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_NOCTOWL] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-8,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-8,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-9,
                .monX=6, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_ARIADOS] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=0,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-8,
                .monX=0, .monY=0,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-6, .playerY=-6,
                .monX=4, .monY=0,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_CROBAT] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-8,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-9,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_LANTURN] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-8,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-2, .playerY=-6,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_AMPHAROS] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-1, .playerY=-5,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_POLITOED] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=0,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=0,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-4,
                .monX=3, .monY=0,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_QUAGSIRE] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-4,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_SLOWKING] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-4,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_WOBBUFFET] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-4,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_GIRAFARIG] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-2, .playerY=-5,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_FORRETRESS] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-3,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-3,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_STEELIX] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=-1, .playerY=-17,
                .monX=0, .monY=-14,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-17,
                .monX=0, .monY=-14,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-2, .playerY=-15,
                .monX=3, .monY=-13,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_GRANBULL] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-4,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_URSARING] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-5,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_MAGCARGO] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-4,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_PILOSWINE] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-4,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_OCTILLERY] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-4,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-4,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_MANTINE] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-9,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-9,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-7,
                .monX=1, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_SKARMORY] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-8,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-10,
                .monX=6, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_HOUNDOOM] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=1, .playerY=-5,
                .monX=0, .monY=0,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=0,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-4,
                .monX=4, .monY=0,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_KINGDRA] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-4,
                .monX=5, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_DONPHAN] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-6,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-6, .playerY=-6,
                .monX=4, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_STANTLER] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-2, .playerY=-5,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_RAIKOU] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-2, .playerY=-6,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_ENTEI] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-8,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-2,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-7,
                .monX=3, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_SUICUNE] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB | RIDE_MON_FLAG_CAN_SWIM,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-3,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-5, .playerY=-6,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_TYRANITAR] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_CLIMB,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-5,
                .monX=0, .monY=1,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-3, .playerY=-5,
                .monX=2, .monY=1,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
        }
    },
    [SPECIES_LUGIA] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_SWIM | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-7,
                .monX=0, .monY=-13,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-8,
                .monX=0, .monY=-12,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-11,
                .monX=3, .monY=-11,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
    [SPECIES_HO_OH] =
    {
        .flags = RIDE_MON_FLAG_CAN_RIDE | RIDE_MON_FLAG_CAN_FLY,
        .spriteInfo = 
        {
            [RIDE_SPRITE_DIR_UP] =
            {
                .playerX=0, .playerY=-3,
                .monX=0, .monY=-10,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_DOWN] =
            {
                .playerX=0, .playerY=-12,
                .monX=0, .monY=-12,
                .playerRendersInFront=RIDER_SHOW_INFRONT,
            },
            [RIDE_SPRITE_DIR_SIDE] =
            {
                .playerX=-4, .playerY=-13,
                .monX=4, .monY=-10,
                .playerRendersInFront=RIDER_SHOW_BEHIND,
            },
        }
    },
};
