// == WARNING ==
// DO NOT EDIT THIS FILE
// This file was automatically generated by PokemonQueryBaker

const struct RogueSpeciesBakedData gRogueBake_SpeciesData[NUM_SPECIES] =
{
	[0] =
	{
		.eggSpecies = 0,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 0,
	},
	[1] =
	{
		.eggSpecies = 1,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2056,
	},
	[2] =
	{
		.eggSpecies = 1,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2056,
	},
	[3] =
	{
		.eggSpecies = 1,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2056,
	},
	[4] =
	{
		.eggSpecies = 4,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 516,
	},
	[5] =
	{
		.eggSpecies = 4,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 516,
	},
	[6] =
	{
		.eggSpecies = 4,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 516,
	},
	[7] =
	{
		.eggSpecies = 7,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1024,
	},
	[8] =
	{
		.eggSpecies = 7,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1024,
	},
	[9] =
	{
		.eggSpecies = 7,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[10] =
	{
		.eggSpecies = 10,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 68,
	},
	[11] =
	{
		.eggSpecies = 10,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 68,
	},
	[12] =
	{
		.eggSpecies = 10,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 68,
	},
	[13] =
	{
		.eggSpecies = 13,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 72,
	},
	[14] =
	{
		.eggSpecies = 13,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 72,
	},
	[15] =
	{
		.eggSpecies = 13,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 72,
	},
	[16] =
	{
		.eggSpecies = 16,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 5,
	},
	[17] =
	{
		.eggSpecies = 16,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 5,
	},
	[18] =
	{
		.eggSpecies = 16,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 5,
	},
	[19] =
	{
		.eggSpecies = 19,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[20] =
	{
		.eggSpecies = 19,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[21] =
	{
		.eggSpecies = 21,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 5,
	},
	[22] =
	{
		.eggSpecies = 21,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 5,
	},
	[23] =
	{
		.eggSpecies = 23,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8,
	},
	[24] =
	{
		.eggSpecies = 23,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8,
	},
	[25] =
	{
		.eggSpecies = 172,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 4096,
	},
	[26] =
	{
		.eggSpecies = 172,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 4096,
	},
	[27] =
	{
		.eggSpecies = 27,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 16,
	},
	[28] =
	{
		.eggSpecies = 27,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 16,
	},
	[29] =
	{
		.eggSpecies = 29,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 24,
	},
	[30] =
	{
		.eggSpecies = 29,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 24,
	},
	[31] =
	{
		.eggSpecies = 29,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 24,
	},
	[32] =
	{
		.eggSpecies = 32,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 24,
	},
	[33] =
	{
		.eggSpecies = 32,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 24,
	},
	[34] =
	{
		.eggSpecies = 32,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 24,
	},
	[35] =
	{
		.eggSpecies = 173,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[36] =
	{
		.eggSpecies = 173,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[37] =
	{
		.eggSpecies = 37,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 512,
	},
	[38] =
	{
		.eggSpecies = 37,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 512,
	},
	[39] =
	{
		.eggSpecies = 174,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[40] =
	{
		.eggSpecies = 174,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[41] =
	{
		.eggSpecies = 41,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 12,
	},
	[42] =
	{
		.eggSpecies = 41,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 12,
	},
	[43] =
	{
		.eggSpecies = 43,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2056,
	},
	[44] =
	{
		.eggSpecies = 43,
		.evolutionCount = 3,
		.evolutionChainTypeFlags = 2056,
	},
	[45] =
	{
		.eggSpecies = 43,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2056,
	},
	[46] =
	{
		.eggSpecies = 46,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2112,
	},
	[47] =
	{
		.eggSpecies = 46,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2112,
	},
	[48] =
	{
		.eggSpecies = 48,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 72,
	},
	[49] =
	{
		.eggSpecies = 48,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 72,
	},
	[50] =
	{
		.eggSpecies = 50,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 16,
	},
	[51] =
	{
		.eggSpecies = 50,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 16,
	},
	[52] =
	{
		.eggSpecies = 52,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[53] =
	{
		.eggSpecies = 52,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[54] =
	{
		.eggSpecies = 54,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1024,
	},
	[55] =
	{
		.eggSpecies = 54,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[56] =
	{
		.eggSpecies = 56,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2,
	},
	[57] =
	{
		.eggSpecies = 56,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2,
	},
	[58] =
	{
		.eggSpecies = 58,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 512,
	},
	[59] =
	{
		.eggSpecies = 58,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 512,
	},
	[60] =
	{
		.eggSpecies = 60,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1026,
	},
	[61] =
	{
		.eggSpecies = 60,
		.evolutionCount = 3,
		.evolutionChainTypeFlags = 1026,
	},
	[62] =
	{
		.eggSpecies = 60,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1026,
	},
	[63] =
	{
		.eggSpecies = 63,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8192,
	},
	[64] =
	{
		.eggSpecies = 63,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8192,
	},
	[65] =
	{
		.eggSpecies = 63,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8192,
	},
	[66] =
	{
		.eggSpecies = 66,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2,
	},
	[67] =
	{
		.eggSpecies = 66,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2,
	},
	[68] =
	{
		.eggSpecies = 66,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2,
	},
	[69] =
	{
		.eggSpecies = 69,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2056,
	},
	[70] =
	{
		.eggSpecies = 69,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2056,
	},
	[71] =
	{
		.eggSpecies = 69,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2056,
	},
	[72] =
	{
		.eggSpecies = 72,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1032,
	},
	[73] =
	{
		.eggSpecies = 72,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1032,
	},
	[74] =
	{
		.eggSpecies = 74,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 48,
	},
	[75] =
	{
		.eggSpecies = 74,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 48,
	},
	[76] =
	{
		.eggSpecies = 74,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 48,
	},
	[77] =
	{
		.eggSpecies = 77,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 512,
	},
	[78] =
	{
		.eggSpecies = 77,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 512,
	},
	[79] =
	{
		.eggSpecies = 79,
		.evolutionCount = 3,
		.evolutionChainTypeFlags = 9216,
	},
	[80] =
	{
		.eggSpecies = 79,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 9216,
	},
	[81] =
	{
		.eggSpecies = 81,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 4352,
	},
	[82] =
	{
		.eggSpecies = 81,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 4352,
	},
	[83] =
	{
		.eggSpecies = 83,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 5,
	},
	[84] =
	{
		.eggSpecies = 84,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 5,
	},
	[85] =
	{
		.eggSpecies = 84,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 5,
	},
	[86] =
	{
		.eggSpecies = 86,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 17408,
	},
	[87] =
	{
		.eggSpecies = 86,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 17408,
	},
	[88] =
	{
		.eggSpecies = 88,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8,
	},
	[89] =
	{
		.eggSpecies = 88,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8,
	},
	[90] =
	{
		.eggSpecies = 90,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 17408,
	},
	[91] =
	{
		.eggSpecies = 90,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 17408,
	},
	[92] =
	{
		.eggSpecies = 92,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 136,
	},
	[93] =
	{
		.eggSpecies = 92,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 136,
	},
	[94] =
	{
		.eggSpecies = 92,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 136,
	},
	[95] =
	{
		.eggSpecies = 95,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 304,
	},
	[96] =
	{
		.eggSpecies = 96,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8192,
	},
	[97] =
	{
		.eggSpecies = 96,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8192,
	},
	[98] =
	{
		.eggSpecies = 98,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1024,
	},
	[99] =
	{
		.eggSpecies = 98,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[100] =
	{
		.eggSpecies = 100,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 4096,
	},
	[101] =
	{
		.eggSpecies = 100,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 4096,
	},
	[102] =
	{
		.eggSpecies = 102,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 10240,
	},
	[103] =
	{
		.eggSpecies = 102,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 10240,
	},
	[104] =
	{
		.eggSpecies = 104,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 16,
	},
	[105] =
	{
		.eggSpecies = 104,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 16,
	},
	[106] =
	{
		.eggSpecies = 236,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2,
	},
	[107] =
	{
		.eggSpecies = 236,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2,
	},
	[108] =
	{
		.eggSpecies = 108,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[109] =
	{
		.eggSpecies = 109,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8,
	},
	[110] =
	{
		.eggSpecies = 109,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8,
	},
	[111] =
	{
		.eggSpecies = 111,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 48,
	},
	[112] =
	{
		.eggSpecies = 111,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 48,
	},
	[113] =
	{
		.eggSpecies = 113,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[114] =
	{
		.eggSpecies = 114,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2048,
	},
	[115] =
	{
		.eggSpecies = 115,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[116] =
	{
		.eggSpecies = 116,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 33792,
	},
	[117] =
	{
		.eggSpecies = 116,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 33792,
	},
	[118] =
	{
		.eggSpecies = 118,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1024,
	},
	[119] =
	{
		.eggSpecies = 118,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[120] =
	{
		.eggSpecies = 120,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 9216,
	},
	[121] =
	{
		.eggSpecies = 120,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 9216,
	},
	[122] =
	{
		.eggSpecies = 122,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8192,
	},
	[123] =
	{
		.eggSpecies = 123,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 324,
	},
	[124] =
	{
		.eggSpecies = 238,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 24576,
	},
	[125] =
	{
		.eggSpecies = 239,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 4096,
	},
	[126] =
	{
		.eggSpecies = 240,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 512,
	},
	[127] =
	{
		.eggSpecies = 127,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 64,
	},
	[128] =
	{
		.eggSpecies = 128,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[129] =
	{
		.eggSpecies = 129,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1028,
	},
	[130] =
	{
		.eggSpecies = 129,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1028,
	},
	[131] =
	{
		.eggSpecies = 131,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 17408,
	},
	[132] =
	{
		.eggSpecies = 132,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[133] =
	{
		.eggSpecies = 133,
		.evolutionCount = 6,
		.evolutionChainTypeFlags = 79361,
	},
	[134] =
	{
		.eggSpecies = 133,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 79361,
	},
	[135] =
	{
		.eggSpecies = 133,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 79361,
	},
	[136] =
	{
		.eggSpecies = 133,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 79361,
	},
	[137] =
	{
		.eggSpecies = 137,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[138] =
	{
		.eggSpecies = 138,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1056,
	},
	[139] =
	{
		.eggSpecies = 138,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1056,
	},
	[140] =
	{
		.eggSpecies = 140,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1056,
	},
	[141] =
	{
		.eggSpecies = 140,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1056,
	},
	[142] =
	{
		.eggSpecies = 142,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 36,
	},
	[143] =
	{
		.eggSpecies = 143,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[144] =
	{
		.eggSpecies = 144,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 16388,
	},
	[145] =
	{
		.eggSpecies = 145,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 4100,
	},
	[146] =
	{
		.eggSpecies = 146,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 516,
	},
	[147] =
	{
		.eggSpecies = 147,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 32772,
	},
	[148] =
	{
		.eggSpecies = 147,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 32772,
	},
	[149] =
	{
		.eggSpecies = 147,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 32772,
	},
	[150] =
	{
		.eggSpecies = 150,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8192,
	},
	[151] =
	{
		.eggSpecies = 151,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8192,
	},
	[152] =
	{
		.eggSpecies = 152,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2048,
	},
	[153] =
	{
		.eggSpecies = 152,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2048,
	},
	[154] =
	{
		.eggSpecies = 152,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2048,
	},
	[155] =
	{
		.eggSpecies = 155,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 512,
	},
	[156] =
	{
		.eggSpecies = 155,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 512,
	},
	[157] =
	{
		.eggSpecies = 155,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 512,
	},
	[158] =
	{
		.eggSpecies = 158,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1024,
	},
	[159] =
	{
		.eggSpecies = 158,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1024,
	},
	[160] =
	{
		.eggSpecies = 158,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[161] =
	{
		.eggSpecies = 161,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[162] =
	{
		.eggSpecies = 161,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[163] =
	{
		.eggSpecies = 163,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 5,
	},
	[164] =
	{
		.eggSpecies = 163,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 5,
	},
	[165] =
	{
		.eggSpecies = 165,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 68,
	},
	[166] =
	{
		.eggSpecies = 165,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 68,
	},
	[167] =
	{
		.eggSpecies = 167,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 72,
	},
	[168] =
	{
		.eggSpecies = 167,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 72,
	},
	[169] =
	{
		.eggSpecies = 41,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 12,
	},
	[170] =
	{
		.eggSpecies = 170,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 5120,
	},
	[171] =
	{
		.eggSpecies = 170,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 5120,
	},
	[172] =
	{
		.eggSpecies = 172,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 4096,
	},
	[173] =
	{
		.eggSpecies = 173,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[174] =
	{
		.eggSpecies = 174,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[175] =
	{
		.eggSpecies = 175,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 5,
	},
	[176] =
	{
		.eggSpecies = 175,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 5,
	},
	[177] =
	{
		.eggSpecies = 177,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8196,
	},
	[178] =
	{
		.eggSpecies = 177,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8196,
	},
	[179] =
	{
		.eggSpecies = 179,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 4096,
	},
	[180] =
	{
		.eggSpecies = 179,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 4096,
	},
	[181] =
	{
		.eggSpecies = 179,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 4096,
	},
	[182] =
	{
		.eggSpecies = 43,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2056,
	},
	[183] =
	{
		.eggSpecies = 350,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1025,
	},
	[184] =
	{
		.eggSpecies = 350,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1025,
	},
	[185] =
	{
		.eggSpecies = 185,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 32,
	},
	[186] =
	{
		.eggSpecies = 60,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1026,
	},
	[187] =
	{
		.eggSpecies = 187,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2052,
	},
	[188] =
	{
		.eggSpecies = 187,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2052,
	},
	[189] =
	{
		.eggSpecies = 187,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2052,
	},
	[190] =
	{
		.eggSpecies = 190,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[191] =
	{
		.eggSpecies = 191,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2048,
	},
	[192] =
	{
		.eggSpecies = 191,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2048,
	},
	[193] =
	{
		.eggSpecies = 193,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 68,
	},
	[194] =
	{
		.eggSpecies = 194,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1040,
	},
	[195] =
	{
		.eggSpecies = 194,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1040,
	},
	[196] =
	{
		.eggSpecies = 133,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 79361,
	},
	[197] =
	{
		.eggSpecies = 133,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 79361,
	},
	[198] =
	{
		.eggSpecies = 198,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 65540,
	},
	[199] =
	{
		.eggSpecies = 79,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 9216,
	},
	[200] =
	{
		.eggSpecies = 200,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 128,
	},
	[201] =
	{
		.eggSpecies = 201,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8192,
	},
	[202] =
	{
		.eggSpecies = 360,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8192,
	},
	[203] =
	{
		.eggSpecies = 203,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8193,
	},
	[204] =
	{
		.eggSpecies = 204,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 320,
	},
	[205] =
	{
		.eggSpecies = 204,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 320,
	},
	[206] =
	{
		.eggSpecies = 206,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[207] =
	{
		.eggSpecies = 207,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 20,
	},
	[208] =
	{
		.eggSpecies = 95,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 304,
	},
	[209] =
	{
		.eggSpecies = 209,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[210] =
	{
		.eggSpecies = 209,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[211] =
	{
		.eggSpecies = 211,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1032,
	},
	[212] =
	{
		.eggSpecies = 123,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 324,
	},
	[213] =
	{
		.eggSpecies = 213,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 96,
	},
	[214] =
	{
		.eggSpecies = 214,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 66,
	},
	[215] =
	{
		.eggSpecies = 215,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 81920,
	},
	[216] =
	{
		.eggSpecies = 216,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[217] =
	{
		.eggSpecies = 216,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[218] =
	{
		.eggSpecies = 218,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 544,
	},
	[219] =
	{
		.eggSpecies = 218,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 544,
	},
	[220] =
	{
		.eggSpecies = 220,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 16400,
	},
	[221] =
	{
		.eggSpecies = 220,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 16400,
	},
	[222] =
	{
		.eggSpecies = 222,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1056,
	},
	[223] =
	{
		.eggSpecies = 223,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1024,
	},
	[224] =
	{
		.eggSpecies = 223,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[225] =
	{
		.eggSpecies = 225,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 16388,
	},
	[226] =
	{
		.eggSpecies = 226,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1028,
	},
	[227] =
	{
		.eggSpecies = 227,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 260,
	},
	[228] =
	{
		.eggSpecies = 228,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 66048,
	},
	[229] =
	{
		.eggSpecies = 228,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 66048,
	},
	[230] =
	{
		.eggSpecies = 116,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 33792,
	},
	[231] =
	{
		.eggSpecies = 231,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 16,
	},
	[232] =
	{
		.eggSpecies = 231,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 16,
	},
	[233] =
	{
		.eggSpecies = 137,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[234] =
	{
		.eggSpecies = 234,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[235] =
	{
		.eggSpecies = 235,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[236] =
	{
		.eggSpecies = 236,
		.evolutionCount = 4,
		.evolutionChainTypeFlags = 2,
	},
	[237] =
	{
		.eggSpecies = 236,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2,
	},
	[238] =
	{
		.eggSpecies = 238,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 24576,
	},
	[239] =
	{
		.eggSpecies = 239,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 4096,
	},
	[240] =
	{
		.eggSpecies = 240,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 512,
	},
	[241] =
	{
		.eggSpecies = 241,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[242] =
	{
		.eggSpecies = 113,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[243] =
	{
		.eggSpecies = 243,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 4096,
	},
	[244] =
	{
		.eggSpecies = 244,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 512,
	},
	[245] =
	{
		.eggSpecies = 245,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[246] =
	{
		.eggSpecies = 246,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 65584,
	},
	[247] =
	{
		.eggSpecies = 246,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 65584,
	},
	[248] =
	{
		.eggSpecies = 246,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 65584,
	},
	[249] =
	{
		.eggSpecies = 249,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8196,
	},
	[250] =
	{
		.eggSpecies = 250,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 516,
	},
	[251] =
	{
		.eggSpecies = 251,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 10240,
	},
	[252] =
	{
		.eggSpecies = 252,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[253] =
	{
		.eggSpecies = 253,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[254] =
	{
		.eggSpecies = 254,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[255] =
	{
		.eggSpecies = 255,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[256] =
	{
		.eggSpecies = 256,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[257] =
	{
		.eggSpecies = 257,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[258] =
	{
		.eggSpecies = 258,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[259] =
	{
		.eggSpecies = 259,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[260] =
	{
		.eggSpecies = 260,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[261] =
	{
		.eggSpecies = 261,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[262] =
	{
		.eggSpecies = 262,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[263] =
	{
		.eggSpecies = 263,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[264] =
	{
		.eggSpecies = 264,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[265] =
	{
		.eggSpecies = 265,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[266] =
	{
		.eggSpecies = 266,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[267] =
	{
		.eggSpecies = 267,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[268] =
	{
		.eggSpecies = 268,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[269] =
	{
		.eggSpecies = 269,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[270] =
	{
		.eggSpecies = 270,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[271] =
	{
		.eggSpecies = 271,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[272] =
	{
		.eggSpecies = 272,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[273] =
	{
		.eggSpecies = 273,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[274] =
	{
		.eggSpecies = 274,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[275] =
	{
		.eggSpecies = 275,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[276] =
	{
		.eggSpecies = 276,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[277] =
	{
		.eggSpecies = 277,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2048,
	},
	[278] =
	{
		.eggSpecies = 277,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2048,
	},
	[279] =
	{
		.eggSpecies = 277,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2048,
	},
	[280] =
	{
		.eggSpecies = 280,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 514,
	},
	[281] =
	{
		.eggSpecies = 280,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 514,
	},
	[282] =
	{
		.eggSpecies = 280,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 514,
	},
	[283] =
	{
		.eggSpecies = 283,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1040,
	},
	[284] =
	{
		.eggSpecies = 283,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1040,
	},
	[285] =
	{
		.eggSpecies = 283,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1040,
	},
	[286] =
	{
		.eggSpecies = 286,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 65536,
	},
	[287] =
	{
		.eggSpecies = 286,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 65536,
	},
	[288] =
	{
		.eggSpecies = 288,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[289] =
	{
		.eggSpecies = 288,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[290] =
	{
		.eggSpecies = 290,
		.evolutionCount = 3,
		.evolutionChainTypeFlags = 76,
	},
	[291] =
	{
		.eggSpecies = 290,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 76,
	},
	[292] =
	{
		.eggSpecies = 290,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 76,
	},
	[293] =
	{
		.eggSpecies = 290,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 76,
	},
	[294] =
	{
		.eggSpecies = 290,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 76,
	},
	[295] =
	{
		.eggSpecies = 295,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 3072,
	},
	[296] =
	{
		.eggSpecies = 295,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 3072,
	},
	[297] =
	{
		.eggSpecies = 295,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 3072,
	},
	[298] =
	{
		.eggSpecies = 298,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 67584,
	},
	[299] =
	{
		.eggSpecies = 298,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 67584,
	},
	[300] =
	{
		.eggSpecies = 298,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 67584,
	},
	[301] =
	{
		.eggSpecies = 301,
		.evolutionCount = 3,
		.evolutionChainTypeFlags = 212,
	},
	[302] =
	{
		.eggSpecies = 301,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 212,
	},
	[303] =
	{
		.eggSpecies = 301,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 212,
	},
	[304] =
	{
		.eggSpecies = 304,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 5,
	},
	[305] =
	{
		.eggSpecies = 304,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 5,
	},
	[306] =
	{
		.eggSpecies = 306,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2050,
	},
	[307] =
	{
		.eggSpecies = 306,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2050,
	},
	[308] =
	{
		.eggSpecies = 308,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[309] =
	{
		.eggSpecies = 309,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1028,
	},
	[310] =
	{
		.eggSpecies = 309,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1028,
	},
	[311] =
	{
		.eggSpecies = 311,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1092,
	},
	[312] =
	{
		.eggSpecies = 311,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1092,
	},
	[313] =
	{
		.eggSpecies = 313,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1024,
	},
	[314] =
	{
		.eggSpecies = 313,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[315] =
	{
		.eggSpecies = 315,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[316] =
	{
		.eggSpecies = 315,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[317] =
	{
		.eggSpecies = 317,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[318] =
	{
		.eggSpecies = 318,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8208,
	},
	[319] =
	{
		.eggSpecies = 318,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8208,
	},
	[320] =
	{
		.eggSpecies = 320,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 32,
	},
	[321] =
	{
		.eggSpecies = 321,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 512,
	},
	[322] =
	{
		.eggSpecies = 322,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 65664,
	},
	[323] =
	{
		.eggSpecies = 323,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1040,
	},
	[324] =
	{
		.eggSpecies = 323,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1040,
	},
	[325] =
	{
		.eggSpecies = 325,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[326] =
	{
		.eggSpecies = 326,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 66560,
	},
	[327] =
	{
		.eggSpecies = 326,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 66560,
	},
	[328] =
	{
		.eggSpecies = 328,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1024,
	},
	[329] =
	{
		.eggSpecies = 328,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[330] =
	{
		.eggSpecies = 330,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 66560,
	},
	[331] =
	{
		.eggSpecies = 330,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 66560,
	},
	[332] =
	{
		.eggSpecies = 332,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 32784,
	},
	[333] =
	{
		.eggSpecies = 332,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 32784,
	},
	[334] =
	{
		.eggSpecies = 332,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 32784,
	},
	[335] =
	{
		.eggSpecies = 335,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2,
	},
	[336] =
	{
		.eggSpecies = 335,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2,
	},
	[337] =
	{
		.eggSpecies = 337,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 4096,
	},
	[338] =
	{
		.eggSpecies = 337,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 4096,
	},
	[339] =
	{
		.eggSpecies = 339,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 528,
	},
	[340] =
	{
		.eggSpecies = 339,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 528,
	},
	[341] =
	{
		.eggSpecies = 341,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 17408,
	},
	[342] =
	{
		.eggSpecies = 341,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 17408,
	},
	[343] =
	{
		.eggSpecies = 341,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 17408,
	},
	[344] =
	{
		.eggSpecies = 344,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 67584,
	},
	[345] =
	{
		.eggSpecies = 344,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 67584,
	},
	[346] =
	{
		.eggSpecies = 346,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 16384,
	},
	[347] =
	{
		.eggSpecies = 346,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 16384,
	},
	[348] =
	{
		.eggSpecies = 348,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8224,
	},
	[349] =
	{
		.eggSpecies = 349,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8224,
	},
	[350] =
	{
		.eggSpecies = 350,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1025,
	},
	[351] =
	{
		.eggSpecies = 351,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8192,
	},
	[352] =
	{
		.eggSpecies = 351,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8192,
	},
	[353] =
	{
		.eggSpecies = 353,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 4096,
	},
	[354] =
	{
		.eggSpecies = 354,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 4096,
	},
	[355] =
	{
		.eggSpecies = 355,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 256,
	},
	[356] =
	{
		.eggSpecies = 356,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8194,
	},
	[357] =
	{
		.eggSpecies = 356,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8194,
	},
	[358] =
	{
		.eggSpecies = 358,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 32773,
	},
	[359] =
	{
		.eggSpecies = 358,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 32773,
	},
	[360] =
	{
		.eggSpecies = 360,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8192,
	},
	[361] =
	{
		.eggSpecies = 361,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 128,
	},
	[362] =
	{
		.eggSpecies = 361,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 128,
	},
	[363] =
	{
		.eggSpecies = 363,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2056,
	},
	[364] =
	{
		.eggSpecies = 364,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[365] =
	{
		.eggSpecies = 364,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[366] =
	{
		.eggSpecies = 364,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[367] =
	{
		.eggSpecies = 367,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8,
	},
	[368] =
	{
		.eggSpecies = 367,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8,
	},
	[369] =
	{
		.eggSpecies = 369,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2052,
	},
	[370] =
	{
		.eggSpecies = 370,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[371] =
	{
		.eggSpecies = 370,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 1,
	},
	[372] =
	{
		.eggSpecies = 370,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[373] =
	{
		.eggSpecies = 373,
		.evolutionCount = 3,
		.evolutionChainTypeFlags = 1024,
	},
	[374] =
	{
		.eggSpecies = 373,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[375] =
	{
		.eggSpecies = 373,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[376] =
	{
		.eggSpecies = 376,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 65536,
	},
	[377] =
	{
		.eggSpecies = 377,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 128,
	},
	[378] =
	{
		.eggSpecies = 377,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 128,
	},
	[379] =
	{
		.eggSpecies = 379,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8,
	},
	[380] =
	{
		.eggSpecies = 380,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[381] =
	{
		.eggSpecies = 381,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1056,
	},
	[382] =
	{
		.eggSpecies = 382,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 288,
	},
	[383] =
	{
		.eggSpecies = 382,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 288,
	},
	[384] =
	{
		.eggSpecies = 382,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 288,
	},
	[385] =
	{
		.eggSpecies = 385,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1,
	},
	[386] =
	{
		.eggSpecies = 386,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 64,
	},
	[387] =
	{
		.eggSpecies = 387,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 64,
	},
	[388] =
	{
		.eggSpecies = 388,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 2080,
	},
	[389] =
	{
		.eggSpecies = 388,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 2080,
	},
	[390] =
	{
		.eggSpecies = 390,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 96,
	},
	[391] =
	{
		.eggSpecies = 390,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 96,
	},
	[392] =
	{
		.eggSpecies = 392,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8192,
	},
	[393] =
	{
		.eggSpecies = 392,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8192,
	},
	[394] =
	{
		.eggSpecies = 392,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8192,
	},
	[395] =
	{
		.eggSpecies = 395,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 32772,
	},
	[396] =
	{
		.eggSpecies = 395,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 32772,
	},
	[397] =
	{
		.eggSpecies = 395,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 32772,
	},
	[398] =
	{
		.eggSpecies = 398,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8448,
	},
	[399] =
	{
		.eggSpecies = 398,
		.evolutionCount = 2,
		.evolutionChainTypeFlags = 8448,
	},
	[400] =
	{
		.eggSpecies = 398,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8448,
	},
	[401] =
	{
		.eggSpecies = 401,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 32,
	},
	[402] =
	{
		.eggSpecies = 402,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 16384,
	},
	[403] =
	{
		.eggSpecies = 403,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 256,
	},
	[404] =
	{
		.eggSpecies = 404,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 1024,
	},
	[405] =
	{
		.eggSpecies = 405,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 16,
	},
	[406] =
	{
		.eggSpecies = 406,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 32772,
	},
	[407] =
	{
		.eggSpecies = 407,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 40960,
	},
	[408] =
	{
		.eggSpecies = 408,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 40960,
	},
	[409] =
	{
		.eggSpecies = 409,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8448,
	},
	[410] =
	{
		.eggSpecies = 410,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8192,
	},
	[411] =
	{
		.eggSpecies = 411,
		.evolutionCount = 0,
		.evolutionChainTypeFlags = 8192,
	},
};


const u8 gRogueBake_PokedexVariantBitFlags[POKEDEX_VARIANT_COUNT][SPECIES_FLAGS_BYTE_COUNT] =
{
	[0] = 
	{
		254,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
	},
	[1] = 
	{
		254,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		15,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
	},
	[2] = 
	{
		0,
		0,
		0,
		30,
		224,
		63,
		192,
		128,
		31,
		31,
		54,
		3,
		48,
		224,
		241,
		131,
		6,
		0,
		0,
		0,
		0,
		94,
		198,
		1,
		0,
		12,
		64,
		76,
		200,
		1,
		0,
		0,
		0,
		0,
		224,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		255,
		15,
	},
};
